import { CARD_CATALOG } from '../../data/cards/basicCards';
import { CHARACTERS } from '../../data/characters/characters';
import { BASIC_ENEMIES } from '../../data/enemies/basicEnemies';
import { BASIC_POTIONS } from '../../data/potions/basicPotions';
import { BASIC_RELICS } from '../../data/relics/basicRelics';
import type { CharacterDefinition, CharacterUpgrades, GameState, MetaProgressState } from '../engine/types';
export const DISCOVERY_POINT_VALUE = 1;
export const HP_UPGRADE_AMOUNT = 2; export const HP_UPGRADE_BASE_LIMIT = 15;
export const STARTER_CARD_UPGRADE_COST = 4; export const STARTER_CARD_UPGRADE_LIMIT = 5;
export const INITIAL_ENERGY_UPGRADE_COST = 10; export const INITIAL_ENERGY_UPGRADE_LIMIT = 1;
export const STARTING_GOLD_UPGRADE_AMOUNT = 10; export const STARTING_GOLD_BASE_LIMIT = 15;
/** Effective HP/Gold upgrade limit: first 10 are always available; 11–15 require difficulty-3 clear. */
export function hpUpgradeLimit(meta: MetaProgressState): number { return meta.maxUnlockedAscensionLevel >= 4 ? HP_UPGRADE_BASE_LIMIT : 10; }
export function goldUpgradeLimit(meta: MetaProgressState): number { return meta.maxUnlockedAscensionLevel >= 4 ? STARTING_GOLD_BASE_LIMIT : 10; }
/** Escalating cost: 1 pt for upgrades 1–5, 2 pt for 6–8, 3 pt for 9–10, 4 pt for 11–15. */
export function hpUpgradeCost(current: number): number { return current < 5 ? 1 : current < 8 ? 2 : current < 10 ? 3 : 4; }
export function goldUpgradeCost(current: number): number { return current < 5 ? 1 : current < 8 ? 2 : current < 10 ? 3 : 4; }
export const emptyCharacterUpgrades = (): CharacterUpgrades => ({ hpUpgrades: 0, starterCardUpgradeIndexes: [], energyUpgrades: 0, goldUpgrades: 0 });
const deckCards = (state: GameState) => state.combat ? [state.combat.deck.drawPile, state.combat.deck.hand, state.combat.deck.discardPile, state.combat.deck.exhaustPile, state.combat.deck.powerPile].flat().map((card) => card.definitionId) : [];
const uniqueKnown = (ids: string[], catalog: Record<string, unknown>) => [...new Set(ids.filter((id) => Boolean(catalog[id])))];
export function emptyCollectionProgress(): Pick<MetaProgressState, 'discoveredCharacterIds' | 'discoveredCardIds' | 'discoveredEnemyIds' | 'discoveredRelicIds' | 'discoveredPotionIds' | 'upgradePoints' | 'characterUpgrades'> { return { discoveredCharacterIds: [], discoveredCardIds: [], discoveredEnemyIds: [], discoveredRelicIds: [], discoveredPotionIds: [], upgradePoints: 0, characterUpgrades: {} }; }
export function recordDiscoveries(state: GameState): GameState { const meta = state.metaProgress; const player = state.player; const observed = { characters: player ? [player.characterId] : [], cards: player ? [...player.deck.map((card) => card.definitionId), ...deckCards(state)] : deckCards(state), enemies: state.combat?.enemies.map((enemy) => enemy.definitionId) ?? [], relics: player ? [...player.relics, ...(state.combat?.relicIds ?? [])] : state.combat?.relicIds ?? [], potions: player ? [...player.potions, ...(state.combat?.potionIds ?? [])] : state.combat?.potionIds ?? [] }; const categories: Array<[keyof typeof observed, keyof Pick<MetaProgressState, 'discoveredCharacterIds' | 'discoveredCardIds' | 'discoveredEnemyIds' | 'discoveredRelicIds' | 'discoveredPotionIds'>, Record<string, unknown>]> = [['characters', 'discoveredCharacterIds', CHARACTERS], ['cards', 'discoveredCardIds', CARD_CATALOG], ['enemies', 'discoveredEnemyIds', BASIC_ENEMIES], ['relics', 'discoveredRelicIds', BASIC_RELICS], ['potions', 'discoveredPotionIds', BASIC_POTIONS]]; let earned = 0; const next = { ...meta }; for (const [observedKey, metaKey, catalog] of categories) { const ids = uniqueKnown(observed[observedKey], catalog); const known = new Set(next[metaKey]); const fresh = ids.filter((id) => !known.has(id)); earned += fresh.length; next[metaKey] = [...next[metaKey], ...fresh]; } return earned ? { ...state, metaProgress: { ...next, upgradePoints: next.upgradePoints + earned * DISCOVERY_POINT_VALUE } } : state; }
export function normalizedCharacterUpgrades(value?: Partial<CharacterUpgrades>): CharacterUpgrades { return { hpUpgrades: Math.min(HP_UPGRADE_BASE_LIMIT, Math.max(0, value?.hpUpgrades ?? 0)), starterCardUpgradeIndexes: [...new Set((value?.starterCardUpgradeIndexes ?? []).filter((index) => Number.isInteger(index) && index >= 0))].slice(0, STARTER_CARD_UPGRADE_LIMIT), energyUpgrades: Math.min(INITIAL_ENERGY_UPGRADE_LIMIT, Math.max(0, value?.energyUpgrades ?? 0)), goldUpgrades: Math.min(STARTING_GOLD_BASE_LIMIT, Math.max(0, value?.goldUpgrades ?? 0)) }; }
export function applyCharacterUpgrades(character: CharacterDefinition, upgrade?: CharacterUpgrades): CharacterDefinition { const current = normalizedCharacterUpgrades(upgrade); return { ...character, maxHp: character.maxHp + current.hpUpgrades * HP_UPGRADE_AMOUNT, baseEnergy: (character.baseEnergy ?? 3) + current.energyUpgrades, startingGold: (character.startingGold ?? 99) + current.goldUpgrades * STARTING_GOLD_UPGRADE_AMOUNT }; }
function canSpend(meta: MetaProgressState, characterId: string, cost: number): boolean { return meta.upgradePoints >= cost && meta.discoveredCharacterIds.includes(characterId) && Boolean(CHARACTERS[characterId]); }
function update(meta: MetaProgressState, characterId: string, cost: number, change: (current: CharacterUpgrades) => CharacterUpgrades): MetaProgressState { const current = normalizedCharacterUpgrades(meta.characterUpgrades[characterId]); return { ...meta, upgradePoints: meta.upgradePoints - cost, characterUpgrades: { ...meta.characterUpgrades, [characterId]: change(current) } }; }
export function spendHpPoint(meta: MetaProgressState, characterId: string): MetaProgressState | null { const current = normalizedCharacterUpgrades(meta.characterUpgrades[characterId]); const limit = hpUpgradeLimit(meta); const cost = hpUpgradeCost(current.hpUpgrades); return !canSpend(meta, characterId, cost) || current.hpUpgrades >= limit ? null : update(meta, characterId, cost, (value) => ({ ...value, hpUpgrades: value.hpUpgrades + 1 })); }
export function spendStarterCardUpgradePoint(meta: MetaProgressState, characterId: string, cardIndex: number): MetaProgressState | null { const character = CHARACTERS[characterId]; const current = normalizedCharacterUpgrades(meta.characterUpgrades[characterId]); return !canSpend(meta, characterId, STARTER_CARD_UPGRADE_COST) || !character || !Number.isInteger(cardIndex) || cardIndex < 0 || cardIndex >= character.startingDeck.length || !CARD_CATALOG[character.startingDeck[cardIndex]] || current.starterCardUpgradeIndexes.includes(cardIndex) || current.starterCardUpgradeIndexes.length >= STARTER_CARD_UPGRADE_LIMIT ? null : update(meta, characterId, STARTER_CARD_UPGRADE_COST, (value) => ({ ...value, starterCardUpgradeIndexes: [...value.starterCardUpgradeIndexes, cardIndex] })); }
export function spendEnergyPoint(meta: MetaProgressState, characterId: string): MetaProgressState | null { const current = normalizedCharacterUpgrades(meta.characterUpgrades[characterId]); return !canSpend(meta, characterId, INITIAL_ENERGY_UPGRADE_COST) || current.energyUpgrades >= INITIAL_ENERGY_UPGRADE_LIMIT ? null : update(meta, characterId, INITIAL_ENERGY_UPGRADE_COST, (value) => ({ ...value, energyUpgrades: value.energyUpgrades + 1 })); }
export function spendGoldPoint(meta: MetaProgressState, characterId: string): MetaProgressState | null { const current = normalizedCharacterUpgrades(meta.characterUpgrades[characterId]); const limit = goldUpgradeLimit(meta); const cost = goldUpgradeCost(current.goldUpgrades); return !canSpend(meta, characterId, cost) || current.goldUpgrades >= limit ? null : update(meta, characterId, cost, (value) => ({ ...value, goldUpgrades: value.goldUpgrades + 1 })); }