import { CARD_CATALOG } from '../../data/cards/basicCards';
import { BASIC_ENEMIES } from '../../data/enemies/basicEnemies';
import { BASIC_POTIONS } from '../../data/potions/basicPotions';
import { BASIC_RELICS } from '../../data/relics/basicRelics';
import { BASIC_STATUSES } from '../../data/statuses/basicStatuses';
import type { CustomContentCategory } from './customContent';
type RecordValue = Record<string, unknown>;
const keys: Record<string, string> = { id: '标识', name: '名称', description: '描述', signature: '特性', maxHp: '最大生命', baseEnergy: '初始能量', startingGold: '初始金币', startingDeck: '起始牌组', startingRelics: '起始遗物', startingPotions: '起始药水', type: '类型', rarity: '稀有度', cost: '费用', target: '目标', effects: '效果', keywords: '关键词', upgrade: '强化', conditions: '条件', behavior: '行为', intents: '行动循环', actions: '复合动作', amount: '数值', label: '行动名称', statusId: '状态标识', duration: '持续回合', hits: '次数', trigger: '触发时机', effect: '效果', initialBlock: '初始格挡', maxHpRange: '生命范围', phases: '阶段', startsAtHpRatio: '阶段生命阈值', cardIds: '卡牌标识', summonIds: '召唤标识', amountRange: '数值范围', stacks: '层数', targetUid: '目标标识', clearAfter: '施加后移除', onDraw: '抽到时效果', cardType: '卡牌类型', percentage: '生命百分比' };
const reverseKeys = Object.fromEntries(Object.entries(keys).map(([key, value]) => [value, key]));
const values: Record<string, string> = { attack: '攻击', skill: '技艺', power: '能力', status: '状态', curse: '诅咒', basic: '基础', common: '普通', uncommon: '罕见', rare: '稀有', special: '特殊', self: '自身', 'single-enemy': '单个敌人', 'all-enemies': '所有敌人', none: '无目标', damage: '伤害', block: '格挡', draw: '抽牌', 'gain-energy': '获得能量', 'lose-energy': '失去能量', heal: '恢复生命', 'self-damage': '自身伤害', 'clear-statuses': '清除状态', 'damage-equal-block': '等同格挡伤害', 'damage-equal-statuses': '等同状态伤害', 'regen-per-living-enemy': '按存活敌人再生', exhaust: '消耗', retain: '保留', ethereal: '虚无', innate: '固有', 'on-combat-start': '战斗开始', 'on-turn-start': '回合开始', 'on-combat-end': '战斗结束', strength: '力量', gold: '金币', energy: '能量', 'max-hp': '最大生命', 'front-enemy': '最前方敌人', defend: '防御', buff: '强化', pollute: '污染', summon: '召唤', idle: '待机', 'only-card-type': '仅卡牌类型', 'hp-below': '生命低于', 'hp-above': '生命高于' };
const reverseValues = Object.fromEntries(Object.entries(values).map(([key, value]) => [value, key]));
const referenceKeys = new Set(['startingDeck', 'startingRelics', 'startingPotions', 'cardIds', 'summonIds', 'statusId']);
const catalogs: Record<string, Record<string, { name?: string }>> = { startingDeck: CARD_CATALOG, cardIds: CARD_CATALOG, startingRelics: BASIC_RELICS, startingPotions: BASIC_POTIONS, summonIds: BASIC_ENEMIES, statusId: BASIC_STATUSES };
const isRecord = (value: unknown): value is RecordValue => typeof value === 'object' && value !== null && !Array.isArray(value);
function labelReference(value: string, key?: string): string { const item = key ? catalogs[key]?.[value] : undefined; return item?.name ? `${item.name}〔${value}〕` : value; }
function restoreReference(value: string): string { const match = /〔([a-z0-9][a-z0-9-]*)〕$/.exec(value); return match ? match[1] : value; }
function display(value: unknown, key?: string): unknown { if (Array.isArray(value)) return value.map((entry) => display(entry, key)); if (isRecord(value)) return Object.fromEntries(Object.entries(value).map(([name, entry]) => [keys[name] ?? name, display(entry, name)])); if (typeof value === 'string') return key && referenceKeys.has(key) ? labelReference(value, key) : values[value] ?? value; return value; }
function internal(value: unknown, key?: string): unknown { if (Array.isArray(value)) return value.map((entry) => internal(entry, key)); if (isRecord(value)) { const seen = new Set<string>(); return Object.fromEntries(Object.entries(value).map(([name, entry]) => { const translated = reverseKeys[name] ?? name; if (!keys[translated]) throw new Error(`未知的中文字段：${name}`); if (seen.has(translated)) throw new Error(`字段重复：${name}`); seen.add(translated); return [translated, internal(entry, translated)]; })); } if (typeof value === 'string') return key && referenceKeys.has(key) ? restoreReference(value) : reverseValues[value] ?? value; return value; }
export function formatCustomContentForEditor(value: unknown): string { return JSON.stringify(display(value), null, 2); }
export function parseCustomContentEditor(text: string): unknown { try { return internal(JSON.parse(text)); } catch (error) { throw new Error(error instanceof Error ? error.message : '中文 JSON 格式无效。'); } }
export function customContentExamples(category: CustomContentCategory): string[] { const examples: Record<CustomContentCategory, string[]> = { characters: ['最大生命：64（高耐久角色）', '初始能量：4（默认 3，可改为 4）', '初始金币：120（默认角色金币的示例）', '起始牌组：使用“星火斩〔strike〕”这类中文标注，可增删并保留重复牌', '起始遗物 / 起始药水：可填“余烬印记〔ember-seal〕”等条目'], cards: ['费用：0（免费技艺）', '稀有度：稀有', '目标：所有敌人', '效果：[{“类型”:“伤害”,“数值”:6,“次数”:2}]（6 点伤害两次）', '强化：可修改费用、描述、效果、关键词或条件'], enemies: ['最大生命：80', '行动循环：[{“类型”:“攻击”,“数值”:12,“行动名称”:“重击 12”}]', '能量行动：{“类型”:“能量”,“数值”:-1,“行动名称”:“抽离能量”}', '阶段生命阈值：0.5（生命低于 50% 后进入下一阶段）', '召唤标识：可使用“灰烬幼兽〔ashling〕”'], relics: ['触发时机：战斗开始 / 回合开始 / 战斗结束（结束效果仅在胜利时结算）', '效果：{“类型”:“格挡”,“数值”:8}（获得格挡）', '效果：{“类型”:“金币”,“数值”:10}（永久金币，通常配合战斗结束）', '效果：{“类型”:“恢复生命”,“数值”:12} 或 {“类型”:“最大生命”,“数值”:5}（最大生命不自动治疗）', '效果：{“类型”:“伤害”,“数值”:6,“目标”:“所有敌人”,“次数”:2}（按力量、虚弱、易伤和格挡结算）', '效果：{“类型”:“能量”,“数值”:1}（战斗开始时提高能量上限）'], potions: ['效果：{“类型”:“恢复生命”,“数值”:18}', '效果：{“类型”:“格挡”,“数值”:15} 或 {“类型”:“金币”,“数值”:25}', '效果：{“类型”:“最大生命”,“数值”:4}（不自动恢复生命）', '效果：{“类型”:“伤害”,“数值”:14,“目标”:“最前方敌人”}', '效果：{“类型”:“伤害”,“数值”:5,“目标”:“所有敌人”,“次数”:2}', '效果：{“类型”:“能量”,“数值”:2} 或 {“类型”:“能量”,“数值”:-1}'] }; return examples[category]; }