import { CHARACTERS } from '../../data/characters/characters';
import { emptyCollectionProgress, normalizedCharacterUpgrades } from '../ascension/collectionEngine';
import { clampDifficulty, isDifficultyLevel } from '../ascension/ascensionTypes';
import type { CardInstance } from '../combat/cardTypes';
import { createCardInstance } from '../combat/deckEngine';
import { GAME_SCHEMA_VERSION, type GameState } from '../engine/types';

export const SAVE_KEY = 'starfall-card-game/save';
interface SaveEnvelope { version: number; savedAt: number; state: unknown; }
export function saveGame(state: GameState, storage: Storage = localStorage): void { storage.setItem(SAVE_KEY, JSON.stringify({ version: GAME_SCHEMA_VERSION, savedAt: Date.now(), state })); }
export function loadGame(storage: Storage = localStorage): GameState | null { const raw = storage.getItem(SAVE_KEY); if (!raw) return null; try { const envelope = JSON.parse(raw) as SaveEnvelope; const migrated = migrate(envelope); return isGameState(migrated) ? migrated : null; } catch { return null; } }
function normalizeUpgradeRecords(value: unknown): Record<string, ReturnType<typeof normalizedCharacterUpgrades>> { if (!value || typeof value !== 'object' || Array.isArray(value)) return {}; return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([id, upgrade]) => { const source = upgrade && typeof upgrade === 'object' ? upgrade as Record<string, unknown> : {}; return [id, normalizedCharacterUpgrades({ hpUpgrades: typeof source.hpUpgrades === 'number' ? source.hpUpgrades : 0, starterCardUpgradeIndexes: Array.isArray(source.starterCardUpgradeIndexes) ? source.starterCardUpgradeIndexes as number[] : [], energyUpgrades: typeof source.energyUpgrades === 'number' ? source.energyUpgrades : 0, goldUpgrades: typeof source.goldUpgrades === 'number' ? source.goldUpgrades : 0 })]; })); }
function legacyAddedCardPointRefund(value: unknown): number { if (!value || typeof value !== 'object' || Array.isArray(value)) return 0; return Object.values(value as Record<string, unknown>).reduce<number>((total, upgrade) => { const source = upgrade && typeof upgrade === 'object' ? upgrade as Record<string, unknown> : {}; return total + (Array.isArray(source.starterCardIds) ? source.starterCardIds.length : 0); }, 0); }
function normalizeToV4(value: Record<string, unknown>): Record<string, unknown> { const player = value.player && typeof value.player === 'object' ? value.player as Record<string, unknown> : null; const meta = value.metaProgress && typeof value.metaProgress === 'object' ? value.metaProgress as Record<string, unknown> : {}; const characterId = typeof player?.characterId === 'string' ? player.characterId : 'wanderer'; const legacyDeck = Array.isArray(player?.deck) ? player.deck.map((card, index) => typeof card === 'string' ? createCardInstance(card, `migrated-${index}`) : card) : []; return { ...value, schemaVersion: 4, player: player ? { ...player, deck: legacyDeck, baseEnergy: typeof player.baseEnergy === 'number' ? player.baseEnergy : (CHARACTERS[characterId]?.baseEnergy ?? 3) } : null, replay: value.replay ? { ...(value.replay as object) } : undefined, metaProgress: { ...meta, ...emptyCollectionProgress(), schemaVersion: 3, ascensionLevel: typeof meta.ascensionLevel === 'number' ? meta.ascensionLevel : 0, unlockedCharacterIds: Array.isArray(meta.unlockedCharacterIds) ? meta.unlockedCharacterIds : [], unlockedCardIds: Array.isArray(meta.unlockedCardIds) ? meta.unlockedCardIds : [], unlockedRelicIds: Array.isArray(meta.unlockedRelicIds) ? meta.unlockedRelicIds : [], achievements: Array.isArray(meta.achievements) ? meta.achievements : [], discoveredCharacterIds: Array.isArray(meta.discoveredCharacterIds) ? meta.discoveredCharacterIds : [], discoveredCardIds: Array.isArray(meta.discoveredCardIds) ? meta.discoveredCardIds : [], discoveredEnemyIds: Array.isArray(meta.discoveredEnemyIds) ? meta.discoveredEnemyIds : [], discoveredRelicIds: Array.isArray(meta.discoveredRelicIds) ? meta.discoveredRelicIds : [], discoveredPotionIds: Array.isArray(meta.discoveredPotionIds) ? meta.discoveredPotionIds : [], upgradePoints: typeof meta.upgradePoints === 'number' ? Math.max(0, meta.upgradePoints) + legacyAddedCardPointRefund(meta.characterUpgrades) : 0, characterUpgrades: normalizeUpgradeRecords(meta.characterUpgrades) } }; }
function normalizeToV5(value: Record<string, unknown>): Record<string, unknown> { const combat = value.combat && typeof value.combat === 'object' ? value.combat as Record<string, unknown> : undefined; return { ...value, schemaVersion: 5, combat: combat ? { ...combat, persistentGoldDelta: typeof combat.persistentGoldDelta === 'number' && Number.isInteger(combat.persistentGoldDelta) && combat.persistentGoldDelta >= 0 ? combat.persistentGoldDelta : 0, persistentMaxHpDelta: typeof combat.persistentMaxHpDelta === 'number' && Number.isInteger(combat.persistentMaxHpDelta) && combat.persistentMaxHpDelta >= 0 ? combat.persistentMaxHpDelta : 0 } : undefined }; }
function normalizeToV6(value: Record<string, unknown>): Record<string, unknown> { const combat = value.combat && typeof value.combat === 'object' ? value.combat as Record<string, unknown> : undefined; const combatPlayer = combat?.player && typeof combat.player === 'object' ? combat.player as Record<string, unknown> : undefined; const blockRetainTurns = typeof combatPlayer?.blockRetainTurns === 'number' && Number.isInteger(combatPlayer.blockRetainTurns) && combatPlayer.blockRetainTurns >= 0 ? combatPlayer.blockRetainTurns : 0; return { ...value, schemaVersion: 6, combat: combat ? { ...combat, player: combatPlayer ? { ...combatPlayer, blockRetainTurns } : combat.player } : undefined }; }
function normalizeToV7(value: Record<string, unknown>): Record<string, unknown> { const meta = value.metaProgress && typeof value.metaProgress === 'object' ? value.metaProgress as Record<string, unknown> : {}; const maxUnlocked = Math.max(3, clampDifficulty(typeof meta.maxUnlockedAscensionLevel === 'number' ? meta.maxUnlockedAscensionLevel : 3)); const selected = Math.min(maxUnlocked, clampDifficulty(typeof meta.ascensionLevel === 'number' ? meta.ascensionLevel : 1)); const run = value.run && typeof value.run === 'object' ? value.run as Record<string, unknown> : null; const runLevel = Math.min(maxUnlocked, clampDifficulty(typeof run?.ascensionLevel === 'number' ? run.ascensionLevel : selected)); const combat = value.combat && typeof value.combat === 'object' ? value.combat as Record<string, unknown> : undefined; return { ...value, schemaVersion: 7, run: run ? { ...run, ascensionLevel: runLevel } : null, combat: combat ? { ...combat, ascensionLevel: runLevel } : undefined, metaProgress: { ...meta, schemaVersion: 4, ascensionLevel: selected, maxUnlockedAscensionLevel: maxUnlocked } }; }
function migrate(envelope: SaveEnvelope): unknown { if (!envelope.state || typeof envelope.state !== 'object') return null; const state = envelope.state as Record<string, unknown>; if (envelope.version === 7) return state; if (envelope.version === 6) return normalizeToV7(state); if (envelope.version === 5) return normalizeToV7(normalizeToV6(state)); if (envelope.version === 4) return normalizeToV7(normalizeToV6(normalizeToV5(state))); if ([1, 2, 3].includes(envelope.version)) return normalizeToV7(normalizeToV6(normalizeToV5(normalizeToV4(state)))); return null; }
function card(value: unknown): value is CardInstance { return Boolean(value) && typeof value === 'object' && typeof (value as CardInstance).uid === 'string' && typeof (value as CardInstance).definitionId === 'string' && typeof (value as CardInstance).upgraded === 'boolean'; }
function isGameState(value: unknown): value is GameState { if (!value || typeof value !== 'object') return false; const state = value as Partial<GameState>; if (state.schemaVersion !== GAME_SCHEMA_VERSION || !['home', 'compendium', 'custom-content', 'character-select', 'map', 'combat', 'reward', 'event', 'shop', 'special', 'run-summary'].includes(state.mode ?? '')) return false; const meta = state.metaProgress; if (!meta || !Array.isArray(meta.unlockedCharacterIds) || !Array.isArray(meta.discoveredCardIds) || !Number.isInteger(meta.upgradePoints) || meta.upgradePoints < 0 || !meta.characterUpgrades || !isDifficultyLevel(meta.ascensionLevel) || !isDifficultyLevel(meta.maxUnlockedAscensionLevel) || meta.maxUnlockedAscensionLevel < 3 || meta.ascensionLevel > meta.maxUnlockedAscensionLevel) return false; if (state.combat && (!isDifficultyLevel(state.combat.ascensionLevel) || !state.combat.player || !Number.isInteger(state.combat.player.blockRetainTurns) || state.combat.player.blockRetainTurns < 0 || !Number.isInteger(state.combat.persistentGoldDelta) || state.combat.persistentGoldDelta < 0 || !Number.isInteger(state.combat.persistentMaxHpDelta) || state.combat.persistentMaxHpDelta < 0)) return false; if (state.player && (!Array.isArray(state.player.deck) || !state.player.deck.every(card) || !Number.isFinite(state.player.hp) || !Number.isFinite(state.player.maxHp) || !Number.isFinite(state.player.gold) || (state.player.baseEnergy !== undefined && (!Number.isInteger(state.player.baseEnergy) || state.player.baseEnergy < 0)))) return false; if (state.run && (!Number.isInteger(state.run.currentAct) || state.run.currentAct < 1 || !['active', 'victory', 'defeat'].includes(state.run.status) || !isDifficultyLevel(state.run.ascensionLevel) || state.run.ascensionLevel > meta.maxUnlockedAscensionLevel)) return false; return true; }
