import { useState } from 'react';
import { CHARACTERS } from '../data/characters/characters';
import { resolveCard } from '../app/presentation';
import { getCustomContentPack } from '../game/content/customContent';
import type { GameState } from '../game/engine/types';

interface CharacterSelectPageProps { state: GameState; onStart: (characterId: string) => void; onBack: () => void; }
export function CharacterSelectPage({ state, onStart, onBack }: CharacterSelectPageProps) {
  const unlocked = state.metaProgress.unlockedCharacterIds; const customCharacterIds = new Set(Object.keys(getCustomContentPack().characters)); const [selectedId, setSelectedId] = useState(unlocked[0] ?? Object.keys(CHARACTERS)[0] ?? 'wanderer'); const selected = CHARACTERS[selectedId] ?? CHARACTERS.wanderer;
  return <main className="run-shell character-shell"><header className="run-header"><div><p className="eyebrow">CHOOSE THE VESSEL</p><h1>选择角色</h1><p className="subtitle">每位远行者将以不同的构筑踏入灰烬边境。</p></div><button className="text-button" onClick={onBack}>返回</button></header><section className="character-grid" aria-label="角色列表">{Object.values(CHARACTERS).map((character) => { const isUnlocked = unlocked.includes(character.id) || customCharacterIds.has(character.id); const isSelected = selected.id === character.id; return <button key={character.id} className={`character-option ${isSelected ? 'selected' : ''}`} disabled={!isUnlocked} aria-pressed={isSelected} onClick={() => setSelectedId(character.id)}><span className={`character-mark character-${character.id}`} aria-hidden="true">{character.name.slice(0, 1)}</span><span><strong>{character.name}</strong><small>{isUnlocked ? `${character.signature ?? '独特契约'} · 生命 ${character.maxHp}` : '此契约尚未解锁'}</small></span></button>; })}</section><section className="panel character-detail"><p className="eyebrow">已选契约</p><h2>{selected.name}</h2><p className="character-description">{selected.description}</p><div className="character-facts"><p><strong>{selected.maxHp}</strong><span>初始生命</span></p><p><strong>{selected.baseEnergy ?? 3}</strong><span>初始能量</span></p><p><strong>{selected.startingDeck.length}</strong><span>起始牌组</span></p><p><strong>{selected.startingRelics.length}</strong><span>随身遗物</span></p></div><p className="deck-preview">起始卡牌：{selected.startingDeck.map((id) => resolveCard(id)?.name ?? id).join('、')}</p><button className="primary-button" onClick={() => onStart(selected.id)}>以 {selected.name} 开始 Run</button></section></main>;
}
