import { useRef, useState, type CSSProperties, type PointerEvent } from 'react';
import { useLocale } from '../app/locale';
import { cardPresentation, enemyPresentation, statusPresentation } from '../app/presentation';
import { CombatantFigure, IntentIcon, type CombatAnimation } from '../components/CombatantFigure';
import { CARD_CATALOG } from '../data/cards/basicCards'; import { CHARACTERS } from '../data/characters/characters'; import { BASIC_POTIONS } from '../data/potions/basicPotions';
import { canPlayCard, resolveCardDefinition } from '../game/combat/cardEngine'; import type { CardDefinition } from '../game/combat/cardTypes'; import type { CombatState } from '../game/combat/combatTypes'; import type { IntentType } from '../game/combat/enemyTypes';
import { RegionScene } from '../components/scene/RegionScene'; import type { BiomeId } from '../data/biomes/biomes';
import { BASIC_STATUSES } from '../data/statuses/basicStatuses'; import { intentTooltip, keywordTooltip, statusTooltip } from '../app/tooltips';
const RESOURCE_IDS = ['ember', 'pack', 'insight', 'stance', 'disorder'];
const BOSS_RESOURCE_IDS = ['meteor-energy', 'cosmic-erosion'];
interface CombatPageProps { combat: CombatState; characterId: string; regionId?: BiomeId; onPlayCard: (uid: string, definition: CardDefinition, targetUid?: string) => void; onEndTurn: () => void; onUsePotion: (potionId: string) => void; onExit: () => void; }
type DragState = { cardUid: string; startX: number; startY: number; x: number; y: number; active: boolean };
const enemyAnimation = (type?: IntentType): CombatAnimation => type === 'attack' ? 'attack' : type === 'defend' ? 'defend' : type === 'summon' ? 'summon' : type ? 'skill' : 'idle';
const cardAnimation = (card: CardDefinition): CombatAnimation => card.type === 'attack' ? 'attack' : card.effects.some((effect) => effect.type === 'block') ? 'defend' : 'skill';
function StatusStrip({ statuses, strength, weak, vulnerable, noStatusLabel }: { statuses?: CombatState['player']['statuses']; strength?: number; weak?: number; vulnerable?: number; noStatusLabel: string }) { const legacy = [{ label: '力量', value: strength }, { label: '虚弱', value: weak }, { label: '易伤', value: vulnerable }].filter((entry) => entry.value); return <div className="status-strip">{statuses?.map((status) => { const info = statusPresentation(status); return <span key={status.id} className={`status-chip status-${status.id}`} title={statusTooltip(status.id, status.stacks, status.duration)}>{info.label} {status.stacks}</span>; })}{!statuses?.length && !legacy.length && <span className="status-empty">{noStatusLabel}</span>}{!statuses?.length && legacy.map((status) => <span key={status.label}>{status.label} {status.value}</span>)}</div>; }

/** Character resource readout: shows a hero's signature resource against its ceiling. */
function ResourceMeters({ statuses, ariaLabel }: { statuses?: CombatState['player']['statuses']; ariaLabel: string }) {
 const meters = (statuses ?? []).filter((status) => RESOURCE_IDS.includes(status.id));
 if (!meters.length) return null;
 return <div className="resource-meters" aria-label={ariaLabel}>{meters.map((status) => { const definition = BASIC_STATUSES[status.id]; const max = definition?.maxStacks ?? status.stacks; return <span key={status.id} className={`resource-meter meter-${status.id}`} title={statusTooltip(status.id, status.stacks)}><b>{definition?.name ?? status.id}</b><i><em style={{ width: `${Math.min(100, status.stacks / Math.max(1, max) * 100)}%` }} /></i><small>{status.stacks}/{max}</small></span>; })}</div>;
}

/** Boss telemetry: current phase plus any boss-scale resource the fight is escalating. */
function BossBanner({ enemy, phaseLabel }: { enemy: CombatState['enemies'][number]; phaseLabel: string }) {
 const phases = enemy.behavior.phases; const info = enemyPresentation(enemy);
 const escalating = (enemy.statuses ?? []).filter((status) => BOSS_RESOURCE_IDS.includes(status.id));
 if (!phases?.length) return null;
 return <div className="boss-banner" role="status"><div className="boss-banner-head"><strong>{info.name}</strong><span>{phaseLabel} · {phases[enemy.phaseIndex]?.label ?? ''}</span></div><div className="boss-phase-track" aria-hidden="true">{phases.map((phase, index) => <i key={phase.id} className={index <= enemy.phaseIndex ? 'reached' : ''} title={phase.label} />)}</div><div className="boss-hp-bar" role="progressbar" aria-label={info.name} aria-valuemin={0} aria-valuemax={enemy.maxHp} aria-valuenow={enemy.hp}><span style={{ width: `${info.health}%` }} /><b>{enemy.hp}/{enemy.maxHp}</b></div>{escalating.map((status) => { const definition = BASIC_STATUSES[status.id]; const max = definition?.maxStacks ?? Math.max(12, status.stacks); return <div key={status.id} className={`boss-resource meter-${status.id}`} title={statusTooltip(status.id, status.stacks)}><b>{definition?.name ?? status.id}</b><i><em style={{ width: `${Math.min(100, status.stacks / max * 100)}%` }} /></i><small>{status.stacks}</small></div>; })}</div>;
}
function BlockBar({ name, block, maxHp, retainTurns = 0, t }: { name: string; block: number; maxHp: number; retainTurns?: number; t: (k: string, v?: Record<string, string | number>) => string }) { const scale = Math.max(1, maxHp, block); const ariaText = retainTurns > 0 ? t('combat.blockRetainAria', { name, turns: retainTurns }) : t('combat.blockAria', { name }); const displayText = retainTurns > 0 ? t('combat.blockRetain', { block, turns: retainTurns }) : t('combat.blockLabel', { block }); return <div className="block-bar" role="progressbar" aria-label={ariaText} aria-valuemin={0} aria-valuemax={scale} aria-valuenow={block}><span style={{ width: `${block / scale * 100}%` }} /><b>{displayText}</b></div>; }
export function CombatPage({ combat, characterId, regionId, onPlayCard, onEndTurn, onUsePotion, onExit }: CombatPageProps) {
 const { t } = useLocale(); const frontEnemy = combat.enemies.find((enemy) => enemy.hp > 0); const ended = combat.phase === 'victory' || combat.phase === 'defeat'; const character = CHARACTERS[characterId] ?? CHARACTERS.wanderer;
 const bossEnemy = combat.enemies.find((enemy) => enemy.behavior.phases?.length && enemy.hp > 0) ?? combat.enemies.find((enemy) => enemy.behavior.phases?.length);
 const [drag, setDrag] = useState<DragState>(); const [playerAction, setPlayerAction] = useState<{ type: CombatAnimation; nonce: number }>({ type: 'idle', nonce: 0 }); const [hitUids, setHitUids] = useState<string[]>([]); const ignoreClick = useRef<string>();
 const draggedInstance = drag && combat.deck.hand.find((card) => card.uid === drag.cardUid); const draggedRaw = draggedInstance && CARD_CATALOG[draggedInstance.definitionId]; const draggedDefinition = draggedInstance && draggedRaw ? resolveCardDefinition(draggedRaw, draggedInstance) : undefined;
 const playable = (definition: CardDefinition) => !ended && canPlayCard(combat, definition) && (definition.target !== 'single-enemy' || Boolean(frontEnemy));
 const play = (uid: string, raw: CardDefinition, definition: CardDefinition) => { if (!playable(definition)) return; const targets = definition.target === 'all-enemies' ? combat.enemies.filter((enemy) => enemy.hp > 0).map((enemy) => enemy.uid) : definition.target === 'single-enemy' && frontEnemy ? [frontEnemy.uid] : []; setHitUids(definition.effects.some((effect) => effect.type === 'damage') ? targets : []); setPlayerAction((current) => ({ type: cardAnimation(definition), nonce: current.nonce + 1 })); onPlayCard(uid, raw, definition.target === 'single-enemy' ? frontEnemy?.uid : undefined); };
 const pointerDown = (event: PointerEvent<HTMLButtonElement>, cardUid: string) => { if (event.button !== 0) return; event.currentTarget.setPointerCapture(event.pointerId); setDrag({ cardUid, startX: event.clientX, startY: event.clientY, x: event.clientX, y: event.clientY, active: false }); };
 const pointerMove = (event: PointerEvent<HTMLButtonElement>) => {
  const cardUid = event.currentTarget.dataset.cardUid;
  const x = event.clientX; const y = event.clientY;
  setDrag((current) => {
   if (!current || current.cardUid !== cardUid) return current;
   return { ...current, x, y, active: current.active || Math.hypot(x - current.startX, y - current.startY) > 8 };
  });
 };
 const pointerEnd = (event: PointerEvent<HTMLButtonElement>, raw: CardDefinition, definition: CardDefinition) => { if (!drag || drag.cardUid !== event.currentTarget.dataset.cardUid) return; if (drag.active) { const element = document.elementFromPoint(event.clientX, event.clientY) as HTMLElement | null; const drop = element?.closest<HTMLElement>('[data-combat-drop]')?.dataset.combatDrop; const enemyDrop = drop === 'enemies' || combat.enemies.some((enemy) => enemy.uid === drop); const valid = definition.target === 'single-enemy' ? drop === frontEnemy?.uid : definition.target === 'all-enemies' ? enemyDrop : drop === 'player'; if (valid) play(drag.cardUid, raw, definition); ignoreClick.current = drag.cardUid; event.preventDefault(); } setDrag(undefined); };
 const endTurn = () => { const incomingAttack = combat.enemies.some((enemy) => enemy.hp > 0 && enemy.intent.type === 'attack'); if (incomingAttack) setPlayerAction((current) => ({ type: 'hurt', nonce: current.nonce + 1 })); setHitUids([]); onEndTurn(); };
 return <main className={`combat-shell combat-phase-${combat.phase}`}><header className="combat-header"><div><p className="eyebrow">{t('combat.turn', { turn: combat.turn })} · {combat.phase === 'player-turn' ? t('combat.playerTurn') : combat.phase === 'enemy-turn' ? t('combat.enemyTurn') : t('combat.ended')}</p><h1>{ended ? (combat.phase === 'victory' ? t('combat.victory') : t('combat.defeat')) : t('combat.corridor')}</h1></div><div className="combat-header-actions"><span>{t('combat.hp')} {combat.player.hp}/{combat.player.maxHp}</span><span>{t('combat.energy')} {combat.energy.current}/{combat.energy.maximum}</span><button className="text-button" disabled={!ended} onClick={onExit}>{t('combat.leaveCombat')}</button></div></header>
 <section className={`combat-stage ${drag?.active ? `is-targeting target-${draggedDefinition?.target}` : ''}`} aria-label={t('combat.scene')}><div className="combat-scene-layer" aria-hidden="true"><RegionScene regionId={regionId} variant="combat" /></div><div className="battle-horizon" aria-hidden="true" />
  <article className="player-unit" data-combat-drop="player"><div className="unit-nameplate"><strong>{character.name}</strong><small>{character.signature}</small></div><CombatantFigure key={`${playerAction.type}-${playerAction.nonce}`} id={characterId} label={character.name} side="player" animation={playerAction.type} /><div className="unit-vitals"><div className="health-bar" role="progressbar" aria-label={t('combat.hpAria', { name: character.name })} aria-valuemin={0} aria-valuemax={combat.player.maxHp} aria-valuenow={combat.player.hp}><span style={{ width: `${combat.player.hp / combat.player.maxHp * 100}%` }} /></div><BlockBar name={character.name} block={combat.player.block} maxHp={combat.player.maxHp} retainTurns={combat.player.blockRetainTurns} t={t} /><p>{combat.player.hp}/{combat.player.maxHp} HP</p><StatusStrip statuses={combat.player.statuses} strength={combat.player.strength} weak={combat.player.weak} vulnerable={combat.player.vulnerable} noStatusLabel={t('combat.noStatus')} /><ResourceMeters statuses={combat.player.statuses} ariaLabel={t('combat.resources')} /></div></article>
  <div className="enemy-formation" data-combat-drop="enemies" aria-label={t('combat.enemyFormation')}>{combat.enemies.map((enemy) => { const info = enemyPresentation(enemy); const front = enemy.uid === frontEnemy?.uid; const protectedRear = enemy.hp > 0 && !front; const animation: CombatAnimation = enemy.hp <= 0 ? 'defeated' : hitUids.includes(enemy.uid) ? 'hurt' : enemyAnimation(enemy.lastAction); return <button type="button" data-combat-drop={enemy.uid} key={enemy.uid} className={`enemy-unit enemy-${enemy.definitionId} ${front ? 'frontline' : 'rearline'} ${protectedRear ? 'protected' : ''} ${enemy.hp <= 0 ? 'defeated' : ''}`} aria-label={`${info.name}，${front ? t('combat.frontTarget') : protectedRear ? t('combat.rearGuard') : t('combat.defeated')}，${info.intent}`} disabled={enemy.hp <= 0 || ended || protectedRear}><span className={`intent-badge intent-${enemy.intent.type}`} title={intentTooltip(enemy.intent.type)}><IntentIcon type={enemy.intent.type} /><b>{enemy.hp > 0 ? info.intent : t('combat.defeated')}</b></span>{front && enemy.hp > 0 && <span className="frontline-label">{t('combat.frontline')}</span>}{protectedRear && <span className="guarded-label">{t('combat.rearLabel')}</span>}<CombatantFigure key={`${enemy.uid}-${combat.turn}-${animation}-${playerAction.nonce}`} id={enemy.definitionId} label={info.name} side="enemy" animation={animation} /><span className="enemy-name">{info.name}</span><div className="health-bar" role="progressbar" aria-label={t('combat.hpAria', { name: info.name })} aria-valuemin={0} aria-valuemax={enemy.maxHp} aria-valuenow={enemy.hp}><span style={{ width: `${info.health}%` }} /></div><BlockBar name={info.name} block={enemy.block} maxHp={enemy.maxHp} t={t} /><small>{enemy.hp}/{enemy.maxHp} HP</small><StatusStrip statuses={enemy.statuses} strength={enemy.strength} noStatusLabel={t('combat.noStatus')} /></button>; })}</div>
 </section>
 {bossEnemy && <BossBanner enemy={bossEnemy} phaseLabel={t('combat.phase', { current: bossEnemy.phaseIndex + 1, total: bossEnemy.behavior.phases?.length ?? 0 })} />}
 <section className="combat-hud"><div className="resource-cluster"><span><b>{t('combat.hp')}</b>{combat.player.hp}/{combat.player.maxHp}</span><span><b>{t('combat.block')}</b>{combat.player.block}{combat.player.blockRetainTurns > 0 ? ` · ${t('combat.retainInfo', { turns: combat.player.blockRetainTurns })}` : ''}</span><span><b>{t('combat.energy')}</b>{combat.energy.current}/{combat.energy.maximum}</span></div><div className="potion-row">{combat.potionIds.map((potionId) => <button className="secondary-button" key={potionId} disabled={ended} onClick={() => onUsePotion(potionId)}>{t('combat.usePotion', { name: BASIC_POTIONS[potionId]?.name ?? potionId })}</button>)}</div></section>
 <section className="hand-heading"><p>{t('combat.handHint')}</p><p>{t('combat.piles', { draw: combat.deck.drawPile.length, discard: combat.deck.discardPile.length, exhaust: combat.deck.exhaustPile.length })}</p></section>
 <section className="hand" aria-label={t('combat.hand')}>{combat.deck.hand.map((card, index) => { const raw = CARD_CATALOG[card.definitionId]; if (!raw) return null; const definition = resolveCardDefinition(raw, card); const info = cardPresentation(definition); const fan = index - (combat.deck.hand.length - 1) / 2; const style = { '--fan-angle': `${fan * 2.4}deg`, '--fan-lift': `${Math.abs(fan) * 2}px` } as CSSProperties; return <button type="button" data-card-uid={card.uid} key={card.uid} style={style} className={`card card-${definition.type} card-rarity-${definition.rarity} ${drag?.cardUid === card.uid && drag.active ? 'drag-source' : ''}`} disabled={!playable(definition)} onPointerDown={(event) => pointerDown(event, card.uid)} onPointerMove={pointerMove} onPointerUp={(event) => pointerEnd(event, raw, definition)} onPointerCancel={() => setDrag(undefined)} onClick={() => { if (ignoreClick.current === card.uid) { ignoreClick.current = undefined; return; } play(card.uid, raw, definition); }}><span className="card-meta">{info.type} · {info.rarity}</span><span className="card-cost">{definition.cost}</span><span className="card-art" aria-hidden="true" /><strong>{definition.name}</strong><small>{definition.description}</small><em>{info.target}{definition.keywords?.length ? ' · ' : ''}{definition.keywords?.map((keyword, keywordIndex) => <b key={keyword} className="card-keyword" title={keywordTooltip(keyword)}>{keywordIndex > 0 ? ' · ' : ''}{keyword}</b>)}</em></button>; })}</section>
 {drag?.active && draggedDefinition && <div className={`drag-ghost card card-${draggedDefinition.type} card-rarity-${draggedDefinition.rarity}`} style={{ left: drag.x, top: drag.y }} aria-hidden="true"><span className="card-cost">{draggedDefinition.cost}</span><span className="card-art" /><strong>{draggedDefinition.name}</strong><small>{draggedDefinition.description}</small></div>}{!ended && <button className="primary-button end-turn" disabled={combat.phase !== 'player-turn'} onClick={endTurn}>{t('combat.endTurn')}</button>}<section className="combat-log" aria-live="polite" aria-label={t('combat.log')}>{combat.log.slice(-5).map((entry, index) => <p key={`${entry}-${index}`}>{entry}</p>)}</section></main>;
}
