import { useRef, useState, type CSSProperties, type PointerEvent } from 'react';
import { cardPresentation, enemyPresentation, statusPresentation } from '../app/presentation';
import { CombatantFigure, IntentIcon, type CombatAnimation } from '../components/CombatantFigure';
import { CARD_CATALOG } from '../data/cards/basicCards'; import { CHARACTERS } from '../data/characters/characters'; import { BASIC_POTIONS } from '../data/potions/basicPotions';
import { canPlayCard, resolveCardDefinition } from '../game/combat/cardEngine'; import type { CardDefinition } from '../game/combat/cardTypes'; import type { CombatState } from '../game/combat/combatTypes'; import type { IntentType } from '../game/combat/enemyTypes';
interface CombatPageProps { combat: CombatState; characterId: string; onPlayCard: (uid: string, definition: CardDefinition, targetUid?: string) => void; onEndTurn: () => void; onUsePotion: (potionId: string) => void; onExit: () => void; }
type DragState = { cardUid: string; startX: number; startY: number; x: number; y: number; active: boolean };
const enemyAnimation = (type?: IntentType): CombatAnimation => type === 'attack' ? 'attack' : type === 'defend' ? 'defend' : type === 'summon' ? 'summon' : type ? 'skill' : 'idle';
const cardAnimation = (card: CardDefinition): CombatAnimation => card.type === 'attack' ? 'attack' : card.effects.some((effect) => effect.type === 'block') ? 'defend' : 'skill';
function StatusStrip({ statuses, strength, weak, vulnerable }: { statuses?: CombatState['player']['statuses']; strength?: number; weak?: number; vulnerable?: number }) { const legacy = [{ label: '力量', value: strength }, { label: '虚弱', value: weak }, { label: '易伤', value: vulnerable }].filter((entry) => entry.value); return <div className="status-strip">{statuses?.map((status) => { const info = statusPresentation(status); return <span key={status.id} title={info.detail}>{info.label} {status.stacks}</span>; })}{!statuses?.length && !legacy.length && <span className="status-empty">无状态</span>}{!statuses?.length && legacy.map((status) => <span key={status.label}>{status.label} {status.value}</span>)}</div>; }
function BlockBar({ name, block, maxHp }: { name: string; block: number; maxHp: number }) { const scale = Math.max(1, maxHp, block); return <div className="block-bar" role="progressbar" aria-label={`${name}格挡值`} aria-valuemin={0} aria-valuemax={scale} aria-valuenow={block}><span style={{ width: `${block / scale * 100}%` }} /><b>格挡 {block}</b></div>; }
export function CombatPage({ combat, characterId, onPlayCard, onEndTurn, onUsePotion, onExit }: CombatPageProps) {
 const frontEnemy = combat.enemies.find((enemy) => enemy.hp > 0); const ended = combat.phase === 'victory' || combat.phase === 'defeat'; const character = CHARACTERS[characterId] ?? CHARACTERS.wanderer;
 const [drag, setDrag] = useState<DragState>(); const [playerAction, setPlayerAction] = useState<{ type: CombatAnimation; nonce: number }>({ type: 'idle', nonce: 0 }); const [hitUids, setHitUids] = useState<string[]>([]); const ignoreClick = useRef<string>();
 const draggedInstance = drag && combat.deck.hand.find((card) => card.uid === drag.cardUid); const draggedRaw = draggedInstance && CARD_CATALOG[draggedInstance.definitionId]; const draggedDefinition = draggedInstance && draggedRaw ? resolveCardDefinition(draggedRaw, draggedInstance) : undefined;
 const playable = (definition: CardDefinition) => !ended && canPlayCard(combat, definition) && (definition.target !== 'single-enemy' || Boolean(frontEnemy));
 const play = (uid: string, raw: CardDefinition, definition: CardDefinition) => { if (!playable(definition)) return; const targets = definition.target === 'all-enemies' ? combat.enemies.filter((enemy) => enemy.hp > 0).map((enemy) => enemy.uid) : definition.target === 'single-enemy' && frontEnemy ? [frontEnemy.uid] : []; setHitUids(definition.effects.some((effect) => effect.type === 'damage') ? targets : []); setPlayerAction((current) => ({ type: cardAnimation(definition), nonce: current.nonce + 1 })); onPlayCard(uid, raw, definition.target === 'single-enemy' ? frontEnemy?.uid : undefined); };
 const pointerDown = (event: PointerEvent<HTMLButtonElement>, cardUid: string) => { if (event.button !== 0) return; event.currentTarget.setPointerCapture(event.pointerId); setDrag({ cardUid, startX: event.clientX, startY: event.clientY, x: event.clientX, y: event.clientY, active: false }); };
 const pointerMove = (event: PointerEvent<HTMLButtonElement>) => {
  const cardUid = event.currentTarget.dataset.cardUid;
  const x = event.clientX; const y = event.clientY;
  setDrag((current) => {
   if (!current || current.cardUid !== cardUid) return current;
   return { ...current, x, y, active: current.active || Math.hypot(x - current.startX, y - current.startY) > 8 };
  });
 };
 const pointerEnd = (event: PointerEvent<HTMLButtonElement>, raw: CardDefinition, definition: CardDefinition) => { if (!drag || drag.cardUid !== event.currentTarget.dataset.cardUid) return; if (drag.active) { const element = document.elementFromPoint(event.clientX, event.clientY) as HTMLElement | null; const drop = element?.closest<HTMLElement>('[data-combat-drop]')?.dataset.combatDrop; const enemyDrop = drop === 'enemies' || combat.enemies.some((enemy) => enemy.uid === drop); const valid = definition.target === 'single-enemy' ? drop === frontEnemy?.uid : definition.target === 'all-enemies' ? enemyDrop : drop === 'player'; if (valid) play(drag.cardUid, raw, definition); ignoreClick.current = drag.cardUid; event.preventDefault(); } setDrag(undefined); };
 const endTurn = () => { const incomingAttack = combat.enemies.some((enemy) => enemy.hp > 0 && enemy.intent.type === 'attack'); if (incomingAttack) setPlayerAction((current) => ({ type: 'hurt', nonce: current.nonce + 1 })); setHitUids([]); onEndTurn(); };
 return <main className={`combat-shell combat-phase-${combat.phase}`}><header className="combat-header"><div><p className="eyebrow">回合 {combat.turn} · {combat.phase === 'player-turn' ? '你的行动' : combat.phase === 'enemy-turn' ? '敌人行动' : '战斗结束'}</p><h1>{ended ? (combat.phase === 'victory' ? '余烬未灭' : '契约崩解') : '黑曜回廊'}</h1></div><div className="combat-header-actions"><span>生命 {combat.player.hp}/{combat.player.maxHp}</span><span>能量 {combat.energy.current}/{combat.energy.maximum}</span><button className="text-button" disabled={!ended} onClick={onExit}>离开战斗</button></div></header>
 <section className={`combat-stage ${drag?.active ? `is-targeting target-${draggedDefinition?.target}` : ''}`} aria-label="战斗场景"><div className="battle-horizon" aria-hidden="true" />
  <article className="player-unit" data-combat-drop="player"><div className="unit-nameplate"><strong>{character.name}</strong><small>{character.signature}</small></div><CombatantFigure key={`${playerAction.type}-${playerAction.nonce}`} id={characterId} label={character.name} side="player" animation={playerAction.type} /><div className="unit-vitals"><div className="health-bar" role="progressbar" aria-label={`${character.name}生命值`} aria-valuemin={0} aria-valuemax={combat.player.maxHp} aria-valuenow={combat.player.hp}><span style={{ width: `${combat.player.hp / combat.player.maxHp * 100}%` }} /></div><BlockBar name={character.name} block={combat.player.block} maxHp={combat.player.maxHp} /><p>{combat.player.hp}/{combat.player.maxHp} HP</p><StatusStrip statuses={combat.player.statuses} strength={combat.player.strength} weak={combat.player.weak} vulnerable={combat.player.vulnerable} /></div></article>
  <div className="enemy-formation" data-combat-drop="enemies" aria-label="敌人阵列">{combat.enemies.map((enemy) => { const info = enemyPresentation(enemy); const front = enemy.uid === frontEnemy?.uid; const protectedRear = enemy.hp > 0 && !front; const animation: CombatAnimation = enemy.hp <= 0 ? 'defeated' : hitUids.includes(enemy.uid) ? 'hurt' : enemyAnimation(enemy.lastAction); return <button type="button" data-combat-drop={enemy.uid} key={enemy.uid} className={`enemy-unit enemy-${enemy.definitionId} ${front ? 'frontline' : 'rearline'} ${protectedRear ? 'protected' : ''} ${enemy.hp <= 0 ? 'defeated' : ''}`} aria-label={`${info.name}，${front ? '最前方目标' : protectedRear ? '受到前排保护' : '已击败'}，${info.intent}`} disabled={enemy.hp <= 0 || ended || protectedRear}><span className={`intent-badge intent-${enemy.intent.type}`}><IntentIcon type={enemy.intent.type} /><b>{enemy.hp > 0 ? info.intent : '已击败'}</b></span>{front && enemy.hp > 0 && <span className="frontline-label">最前方</span>}{protectedRear && <span className="guarded-label">前排保护</span>}<CombatantFigure key={`${enemy.uid}-${combat.turn}-${animation}-${playerAction.nonce}`} id={enemy.definitionId} label={info.name} side="enemy" animation={animation} /><span className="enemy-name">{info.name}</span><div className="health-bar" role="progressbar" aria-label={`${info.name}生命值`} aria-valuemin={0} aria-valuemax={enemy.maxHp} aria-valuenow={enemy.hp}><span style={{ width: `${info.health}%` }} /></div><BlockBar name={info.name} block={enemy.block} maxHp={enemy.maxHp} /><small>{enemy.hp}/{enemy.maxHp} HP</small><StatusStrip statuses={enemy.statuses} strength={enemy.strength} /></button>; })}</div>
 </section>
 <section className="combat-hud"><div className="resource-cluster"><span><b>生命</b>{combat.player.hp}/{combat.player.maxHp}</span><span><b>格挡</b>{combat.player.block}</span><span><b>能量</b>{combat.energy.current}/{combat.energy.maximum}</span></div><div className="potion-row">{combat.potionIds.map((potionId) => <button className="secondary-button" key={potionId} disabled={ended} onClick={() => onUsePotion(potionId)}>使用 {BASIC_POTIONS[potionId]?.name ?? potionId}</button>)}</div></section>
 <section className="hand-heading"><p>拖拽卡牌至发光目标，或点击直接使用 · 单目标始终命中最前方</p><p>抽牌 {combat.deck.drawPile.length} · 弃牌 {combat.deck.discardPile.length} · 消耗 {combat.deck.exhaustPile.length}</p></section>
 <section className="hand" aria-label="手牌">{combat.deck.hand.map((card, index) => { const raw = CARD_CATALOG[card.definitionId]; if (!raw) return null; const definition = resolveCardDefinition(raw, card); const info = cardPresentation(definition); const fan = index - (combat.deck.hand.length - 1) / 2; const style = { '--fan-angle': `${fan * 2.4}deg`, '--fan-lift': `${Math.abs(fan) * 2}px` } as CSSProperties; return <button type="button" data-card-uid={card.uid} key={card.uid} style={style} className={`card card-${definition.type} ${drag?.cardUid === card.uid && drag.active ? 'drag-source' : ''}`} disabled={!playable(definition)} onPointerDown={(event) => pointerDown(event, card.uid)} onPointerMove={pointerMove} onPointerUp={(event) => pointerEnd(event, raw, definition)} onPointerCancel={() => setDrag(undefined)} onClick={() => { if (ignoreClick.current === card.uid) { ignoreClick.current = undefined; return; } play(card.uid, raw, definition); }}><span className="card-meta">{info.type} · {info.rarity}</span><span className="card-cost">{definition.cost}</span><strong>{definition.name}</strong><small>{definition.description}</small><em>{info.target}{definition.keywords?.length ? ` · ${definition.keywords.join(' · ')}` : ''}</em></button>; })}</section>
 {drag?.active && draggedDefinition && <div className={`drag-ghost card card-${draggedDefinition.type}`} style={{ left: drag.x, top: drag.y }} aria-hidden="true"><span className="card-cost">{draggedDefinition.cost}</span><strong>{draggedDefinition.name}</strong><small>{draggedDefinition.description}</small></div>}{!ended && <button className="primary-button end-turn" disabled={combat.phase !== 'player-turn'} onClick={endTurn}>结束回合</button>}<section className="combat-log" aria-live="polite" aria-label="战斗日志">{combat.log.slice(-5).map((entry, index) => <p key={`${entry}-${index}`}>{entry}</p>)}</section></main>;
}
