import { useState, type ReactNode } from 'react';
import { CARD_CATALOG } from '../data/cards/basicCards';
import { CHARACTERS } from '../data/characters/characters';
import { BASIC_ENEMIES } from '../data/enemies/basicEnemies';
import { BASIC_POTIONS } from '../data/potions/basicPotions';
import { BASIC_RELICS } from '../data/relics/basicRelics';
import { BASIC_STATUSES } from '../data/statuses/basicStatuses';
import { RARITY_LABEL } from '../game/relics/relicTypes';
import { sourceText } from '../game/run/contentSources';
import { HP_UPGRADE_AMOUNT, HP_UPGRADE_LIMIT, INITIAL_ENERGY_UPGRADE_COST, INITIAL_ENERGY_UPGRADE_LIMIT, normalizedCharacterUpgrades, STARTER_CARD_UPGRADE_COST, STARTER_CARD_UPGRADE_LIMIT, STARTING_GOLD_UPGRADE_AMOUNT, STARTING_GOLD_UPGRADE_LIMIT } from '../game/ascension/collectionEngine';
import type { GameState } from '../game/engine/types';
type Category = 'characters' | 'cards' | 'enemies' | 'relics' | 'potions';
interface Props { state: GameState; onBack: () => void; onUpgradeHp: (characterId: string) => void; onUpgradeStarterCard: (characterId: string, cardIndex: number) => void; onUpgradeEnergy: (characterId: string) => void; onUpgradeGold: (characterId: string) => void; }
const labels: Record<Category, string> = { characters: '角色特性', cards: '卡牌', enemies: '怪物', relics: '遗物', potions: '药水' };
const intents = (enemy: (typeof BASIC_ENEMIES)[string]) => [...enemy.behavior.intents, ...(enemy.behavior.phases?.flatMap((phase) => phase.intents) ?? [])].map((intent) => intent.label).filter((label, index, values) => values.indexOf(label) === index).join(' · ');
const itemEffectText = (effect: (typeof BASIC_RELICS)[string]['effect']) => {
 switch (effect.type) {
  case 'strength': return `力量 +${effect.amount}`;
  case 'block': return `格挡 +${effect.amount}`;
  case 'gold': return `金币 +${effect.amount}`;
  case 'energy': return `能量 ${effect.amount >= 0 ? '+' : ''}${effect.amount}`;
  case 'heal': return `恢复生命 +${effect.amount}`;
  case 'max-hp': return `最大生命 +${effect.amount}`;
  case 'damage': return `伤害 ${effect.amount}${effect.hits && effect.hits > 1 ? ` ×${effect.hits}` : ''}（${effect.target === 'all-enemies' ? '所有敌人' : '最前方敌人'}）`;
  case 'draw': return `抽牌 ${effect.amount}`;
  case 'apply-status': return `${BASIC_STATUSES[effect.statusId]?.name ?? effect.statusId} ${effect.amount}${effect.duration ? ` · ${effect.duration} 回合` : ''}（${effect.target === 'all-enemies' ? '所有敌人' : '自身'}）`;
  case 'cleanse': return `净化：${effect.statusIds.map((id) => BASIC_STATUSES[id]?.name ?? id).join('、')}`;
 }
};
const CARD_RARITY_LABEL: Record<string, string> = { basic: '基础', common: '普通', uncommon: '罕见', rare: '稀有', special: '特殊' };
function rarityText(rarity?: string): string { return rarity ? CARD_RARITY_LABEL[rarity] ?? RARITY_LABEL[rarity as keyof typeof RARITY_LABEL] ?? rarity : '普通'; }
function StateMark({ discovered }: { discovered: boolean }) { return <span className={`collection-state ${discovered ? 'discovered' : ''}`}>{discovered ? '已收集 · +1 点' : '未收集'}</span>; }
function CollectionEntry({ discovered, children }: { discovered: boolean; children: ReactNode }) { return <article className={`collection-entry ${discovered ? 'is-discovered' : 'is-undiscovered'}`}>{children}<StateMark discovered={discovered} /></article>; }
export function CompendiumPage({ state, onBack, onUpgradeHp, onUpgradeStarterCard, onUpgradeEnergy, onUpgradeGold }: Props) {
 const [category, setCategory] = useState<Category>('characters'); const meta = state.metaProgress; const tab = (id: Category, discovered: number, total: number) => <button key={id} className={`collection-tab ${category === id ? 'selected' : ''}`} aria-pressed={category === id} onClick={() => setCategory(id)}>{labels[id]} <span>{discovered}/{total}</span></button>; const cards = Object.values(CARD_CATALOG); const enemies = Object.values(BASIC_ENEMIES); const relics = Object.values(BASIC_RELICS); const potions = Object.values(BASIC_POTIONS);
 return <main className="run-shell compendium-shell"><header className="run-header"><div><p className="eyebrow">ASHEN ARCHIVE · COLLECTION</p><h1>余烬图鉴</h1><p className="subtitle">未收集内容以灰色标记，但完整属性始终可查。每项首次收集都会获得 1 点升级点。</p></div><button className="text-button" onClick={onBack}>返回主菜单</button></header><section className="collection-summary panel"><span>升级点</span><strong>{meta.upgradePoints}</strong><p>角色可强化生命、起始卡牌、初始能量与起始金币；强化只在下一次新 Run 生效。</p></section><nav className="collection-tabs" aria-label="图鉴分类">{tab('characters', meta.discoveredCharacterIds.length, Object.keys(CHARACTERS).length)}{tab('cards', meta.discoveredCardIds.length, cards.length)}{tab('enemies', meta.discoveredEnemyIds.length, enemies.length)}{tab('relics', meta.discoveredRelicIds.length, relics.length)}{tab('potions', meta.discoveredPotionIds.length, potions.length)}</nav>
 {category === 'characters' && <section className="collection-grid">{Object.values(CHARACTERS).map((character) => { const discovered = meta.discoveredCharacterIds.includes(character.id); const upgrades = normalizedCharacterUpgrades(meta.characterUpgrades[character.id]); const canSpend = (cost: number) => discovered && meta.upgradePoints >= cost; return <CollectionEntry key={character.id} discovered={discovered}><p className="eyebrow">{character.signature ?? '远征契约'}</p><h2>{character.name}</h2><p>{character.description}</p><dl><div><dt>初始生命</dt><dd>{character.maxHp + upgrades.hpUpgrades * HP_UPGRADE_AMOUNT}（+{upgrades.hpUpgrades * HP_UPGRADE_AMOUNT}/20）</dd></div><div><dt>初始能量</dt><dd>{(character.baseEnergy ?? 3) + upgrades.energyUpgrades}（+{upgrades.energyUpgrades}/1）</dd></div><div><dt>起始金币</dt><dd>{(character.startingGold ?? 99) + upgrades.goldUpgrades * STARTING_GOLD_UPGRADE_AMOUNT}（+{upgrades.goldUpgrades * STARTING_GOLD_UPGRADE_AMOUNT}/100）</dd></div><div><dt>起始牌组</dt><dd>{character.startingDeck.length} 张；已强化 {upgrades.starterCardUpgradeIndexes.length}/{STARTER_CARD_UPGRADE_LIMIT}</dd></div><div><dt>起始遗物</dt><dd>{character.startingRelics.map((id) => BASIC_RELICS[id]?.name ?? id).join('、') || '无'}</dd></div></dl><div className="collection-upgrades"><button className="secondary-button" disabled={!canSpend(1) || upgrades.hpUpgrades >= HP_UPGRADE_LIMIT} onClick={() => onUpgradeHp(character.id)}>1 点：初始生命 +{HP_UPGRADE_AMOUNT}（{upgrades.hpUpgrades}/{HP_UPGRADE_LIMIT}）</button><button className="secondary-button" disabled={!canSpend(INITIAL_ENERGY_UPGRADE_COST) || upgrades.energyUpgrades >= INITIAL_ENERGY_UPGRADE_LIMIT} onClick={() => onUpgradeEnergy(character.id)}>{INITIAL_ENERGY_UPGRADE_COST} 点：初始能量 +1（{upgrades.energyUpgrades}/{INITIAL_ENERGY_UPGRADE_LIMIT}）</button><button className="secondary-button" disabled={!canSpend(1) || upgrades.goldUpgrades >= STARTING_GOLD_UPGRADE_LIMIT} onClick={() => onUpgradeGold(character.id)}>1 点：起始金币 +{STARTING_GOLD_UPGRADE_AMOUNT}（{upgrades.goldUpgrades}/{STARTING_GOLD_UPGRADE_LIMIT}）</button><div className="starter-card-upgrades">{character.startingDeck.map((cardId, index) => { const isUpgraded = upgrades.starterCardUpgradeIndexes.includes(index); return <button key={`${cardId}-${index}`} className="text-button" disabled={!canSpend(STARTER_CARD_UPGRADE_COST) || isUpgraded || upgrades.starterCardUpgradeIndexes.length >= STARTER_CARD_UPGRADE_LIMIT} onClick={() => onUpgradeStarterCard(character.id, index)}>{isUpgraded ? '✓ 已强化' : `${STARTER_CARD_UPGRADE_COST} 点：强化`} #{index + 1} {CARD_CATALOG[cardId]?.name ?? cardId}</button>; })}</div></div></CollectionEntry>; })}</section>}
 {category === 'cards' && <section className="collection-grid">{cards.map((card) => <CollectionEntry key={card.id} discovered={meta.discoveredCardIds.includes(card.id)}><p className="eyebrow">{card.type} · {rarityText(card.rarity)} · {card.target}</p><h2>{card.name}<span className="collection-cost">{card.cost}</span></h2><p>{card.description}</p><dl><div><dt>关键词</dt><dd>{card.keywords?.join('、') || '无'}</dd></div><div><dt>升级</dt><dd>{card.upgrade?.description ?? '无额外升级描述'}</dd></div><div><dt>出处</dt><dd>{sourceText('cards', card.id)}</dd></div></dl></CollectionEntry>)}</section>}
 {category === 'enemies' && <section className="collection-grid">{enemies.map((enemy) => <CollectionEntry key={enemy.id} discovered={meta.discoveredEnemyIds.includes(enemy.id)}><p className="eyebrow">敌对单位</p><h2>{enemy.name}</h2><dl><div><dt>生命</dt><dd>{enemy.maxHpRange ? `${enemy.maxHpRange[0]}–${enemy.maxHpRange[1]}` : enemy.maxHp}</dd></div><div><dt>初始格挡</dt><dd>{enemy.initialBlock ?? 0}</dd></div><div><dt>行动</dt><dd>{intents(enemy) || '无记录'}</dd></div><div><dt>出处</dt><dd>{sourceText('enemies', enemy.id)}</dd></div></dl></CollectionEntry>)}</section>}
 {category === 'relics' && <section className="collection-grid">{relics.map((relic) => <CollectionEntry key={relic.id} discovered={meta.discoveredRelicIds.includes(relic.id)}><p className="eyebrow">{relic.trigger} · {rarityText(relic.rarity)}</p><h2>{relic.name}</h2><p>{relic.description}</p><dl><div><dt>效果</dt><dd>{itemEffectText(relic.effect)}</dd></div><div><dt>出处</dt><dd>{sourceText('relics', relic.id)}</dd></div></dl></CollectionEntry>)}</section>}
 {category === 'potions' && <section className="collection-grid">{potions.map((potion) => <CollectionEntry key={potion.id} discovered={meta.discoveredPotionIds.includes(potion.id)}><p className="eyebrow">消耗品 · {rarityText(potion.rarity)}</p><h2>{potion.name}</h2><p>{potion.description}</p><dl><div><dt>效果</dt><dd>{itemEffectText(potion.effect)}</dd></div><div><dt>出处</dt><dd>{sourceText('potions', potion.id)}</dd></div></dl></CollectionEntry>)}</section>}
 </main>;
}