import { useMemo, useRef, useState } from 'react';
import { CARD_CATALOG } from '../data/cards/basicCards';
import { CHARACTERS } from '../data/characters/characters';
import { BASIC_ENEMIES } from '../data/enemies/basicEnemies';
import { BASIC_POTIONS } from '../data/potions/basicPotions';
import { BASIC_RELICS } from '../data/relics/basicRelics';
import { createCustomContentTemplate, exportCustomContentJson, exportCustomContentTypeScript, getCustomContentPack, importCustomContent, removeCustomContentEntry, type CustomContentCategory, updateCustomContentEntry } from '../game/content/customContent';
import { customContentExamples, formatCustomContentForEditor, parseCustomContentEditor } from '../game/content/customContentEditorTranslation';
interface Props { onBack: () => void; }
const categories: { id: CustomContentCategory; label: string }[] = [{ id: 'characters', label: '角色' }, { id: 'cards', label: '卡牌' }, { id: 'enemies', label: '敌人' }, { id: 'relics', label: '遗物' }, { id: 'potions', label: '药水' }];
const registryFor = (category: CustomContentCategory): Record<string, unknown> => ({ cards: CARD_CATALOG, characters: CHARACTERS, enemies: BASIC_ENEMIES, relics: BASIC_RELICS, potions: BASIC_POTIONS })[category] as Record<string, unknown>;
function entryLabel(value: unknown, fallback: string): string { return typeof value === 'object' && value !== null && typeof (value as { name?: unknown }).name === 'string' ? (value as { name: string }).name : fallback; }
function download(name: string, text: string): void { const url = URL.createObjectURL(new Blob([text], { type: 'application/json' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); }
export function CustomContentPage({ onBack }: Props) {
 const [category, setCategory] = useState<CustomContentCategory>('cards'); const [selectedId, setSelectedId] = useState('strike'); const [editor, setEditor] = useState(() => formatCustomContentForEditor(CARD_CATALOG.strike)); const [notice, setNotice] = useState('编辑器使用中文字段和中文枚举；保存时会安全转回内部数据。'); const [revision, setRevision] = useState(0); const importRef = useRef<HTMLInputElement>(null); const examples = customContentExamples(category);
 const entries = useMemo(() => Object.entries(registryFor(category)).sort(([left], [right]) => left.localeCompare(right)), [category, revision]);
 const select = (id: string) => { const value = registryFor(category)[id]; setSelectedId(id); setEditor(formatCustomContentForEditor(value)); setNotice(`正在编辑 ${entryLabel(value, id)}。`); };
 const switchCategory = (next: CustomContentCategory) => { const first = Object.keys(registryFor(next))[0]; setCategory(next); if (first) { setSelectedId(first); setEditor(formatCustomContentForEditor(registryFor(next)[first])); } };
 const save = () => { try { const value = parseCustomContentEditor(editor) as { id?: string }; if (!value.id) throw new Error('条目必须包含“标识”。'); updateCustomContentEntry(category, value); setSelectedId(value.id); setEditor(formatCustomContentForEditor(registryFor(category)[value.id])); setRevision((value) => value + 1); setNotice(`已保存 ${value.id}，会在新战斗和图鉴中生效。`); } catch (error) { setNotice(`未保存：${error instanceof Error ? error.message : '中文 JSON 无效。'}`); } };
 const create = () => { const value = createCustomContentTemplate(category); setSelectedId(value.id); setEditor(formatCustomContentForEditor(value)); setNotice('已创建中文模板；修改属性、数值、效果或起始配置后点击保存。'); };
 const revert = () => { try { const pack = getCustomContentPack(); if (!pack[category][selectedId]) throw new Error('当前条目没有自定义覆盖。'); removeCustomContentEntry(category, selectedId); const value = registryFor(category)[selectedId]; setEditor(formatCustomContentForEditor(value)); setRevision((value) => value + 1); setNotice(`已恢复 ${selectedId} 的内置定义。`); } catch (error) { setNotice(error instanceof Error ? error.message : '无法恢复。'); } };
 const importFile = async (file?: File) => { if (!file) return; try { importCustomContent(await file.text()); setRevision((value) => value + 1); const first = Object.keys(registryFor(category))[0]; if (first) select(first); setNotice('导入成功：内容已验证并写入本地存储。导出/导入文件保持标准内部 JSON 格式。'); } catch (error) { setNotice(`导入被拒绝，现有内容未改变：${error instanceof Error ? error.message : '格式无效。'}`); } finally { if (importRef.current) importRef.current.value = ''; } };
 return <main className="run-shell custom-content-shell"><header className="run-header"><div><p className="eyebrow">ASHEN WORKBENCH · LOCAL CONTENT</p><h1>自定义内容</h1><p className="subtitle">编辑器将字段、枚举和已有内容引用转译为中文；保存、导入和对局始终使用已验证的内部数据。</p></div><button className="text-button" onClick={onBack}>返回主菜单</button></header><section className="custom-warning panel"><strong>本地内容包</strong><span>角色可直接编辑“起始牌组 / 起始遗物 / 起始药水”；其中已有内容会显示为“名称〔稳定标识〕”。</span></section><section className="custom-layout"><aside className="custom-browser panel"><nav className="custom-category-tabs" aria-label="内容类型">{categories.map((item) => <button key={item.id} className={`secondary-button ${category === item.id ? 'selected' : ''}`} aria-pressed={category === item.id} onClick={() => switchCategory(item.id)}>{item.label}</button>)}</nav><div className="custom-entry-list" aria-label="内容条目">{entries.map(([id, value]) => <button key={id} className={`text-button ${selectedId === id ? 'selected' : ''}`} onClick={() => select(id)}>{entryLabel(value, id)} <small>{id}</small></button>)}</div><button className="secondary-button" onClick={create}>+ 新建 {categories.find((item) => item.id === category)?.label}</button></aside><section className="custom-editor panel"><div className="custom-editor-head"><div><p className="eyebrow">中文 JSON 定义</p><strong>{selectedId}</strong></div><div><button className="secondary-button" onClick={revert}>恢复内置</button><button className="primary-button" onClick={save}>保存本地修改</button></div></div><label className="custom-textarea-label">完整条目 JSON<textarea value={editor} onChange={(event) => setEditor(event.target.value)} spellCheck={false} aria-label="中文自定义内容 JSON" /></label><details className="custom-examples"><summary>当前类别的属性与数值示例</summary><ul>{examples.map((example) => <li key={example}>{example}</li>)}</ul></details><p className="custom-notice" role="status">{notice}</p><div className="custom-transfer"><button className="secondary-button" onClick={() => download('starfall-content.json', exportCustomContentJson())}>导出 JSON</button><button className="secondary-button" onClick={() => download('starfall-content.ts', exportCustomContentTypeScript())}>导出代码格式</button><input ref={importRef} type="file" accept="application/json,.json,.ts,text/plain" onChange={(event) => void importFile(event.target.files?.[0])} /><button className="secondary-button" onClick={() => importRef.current?.click()}>导入内容包</button></div></section></section></main>;
}