import { useState } from 'react';
import { useLocale } from '../app/locale';
import { CHANGELOG } from '../app/changelog';
import { GameModal } from '../components/GameModal';
import type { GameState } from '../game/engine/types';

interface HomePageProps { state: GameState; onNewRun: () => void; onContinue: () => void; onOpenCompendium: () => void; onOpenCustomContent: () => void; onOpenMonsterCompendium: () => void; onClearSave: () => void; }
function HomeCosmos() { return <div className="home-cosmos" aria-hidden="true"><span className="home-eclipse" /><span className="home-rune-ring rune-ring-a" /><span className="home-rune-ring rune-ring-b" /><span className="home-meteor meteor-a" /><span className="home-meteor meteor-b" /><span className="home-meteor meteor-c" /><svg className="home-constellation" viewBox="0 0 300 300"><path d="M37 226L109 157 176 199 247 74M109 157L143 71M176 199L237 238" /><circle cx="37" cy="226" r="3" /><circle cx="109" cy="157" r="4" /><circle cx="143" cy="71" r="3" /><circle cx="176" cy="199" r="3" /><circle cx="247" cy="74" r="4" /><circle cx="237" cy="238" r="2.5" /></svg><span className="home-halo" /></div>; }
export function HomePage({ state, onNewRun, onContinue, onOpenCompendium, onOpenCustomContent, onOpenMonsterCompendium, onClearSave }: HomePageProps) {
 const { locale, toggleLocale, t } = useLocale(); const [changelogOpen, setChangelogOpen] = useState(false); const hasSave = state.run?.status === 'active'; const meta = state.metaProgress;
 const collected = meta.discoveredCharacterIds.length + meta.discoveredCardIds.length + meta.discoveredEnemyIds.length + meta.discoveredRelicIds.length + meta.discoveredPotionIds.length;
 const changelogText = (msg: string) => { const parts = msg.split('-/-'); return locale === 'en' ? (parts[1] ?? parts[0]) : parts[0]; };
 return <main className="home-shell home-landing"><HomeCosmos /><button className="locale-toggle" type="button" onClick={toggleLocale} aria-label={t('language.switch')} title={t('language.switch')}><span aria-hidden="true">✦</span><b>{t('language.short')}</b><small>{locale === 'zh-CN' ? '中文' : 'ENGLISH'}</small></button><div className="home-layout"><section className="title-block home-hero"><p className="eyebrow">THE CINDER EXPEDITION · VII</p><div className="title-sigil home-sigil" aria-hidden="true"><span>✦</span></div><h1>{locale === 'zh-CN' ? '星陨牌局' : 'Starfall Deckbuilder'}</h1><p className="subtitle">{t('home.subtitle')}</p><p className="world-note">{t('home.worldNote')}</p><div className="home-hero-rule"><span>EMBER / ORBITAL RECORD</span><i /></div><div className="home-ritual-readout" aria-label={t('home.readout')}><span><b>07</b>{t('home.year')}</span><span><b>Ⅰ</b>{t('home.anchor')}</span><span><b>◌</b>{t('home.silence')}</span></div></section><section className="menu-card home-command-card" aria-label={t('home.menu')}><header className="home-command-head"><span className="home-command-mark" aria-hidden="true">✦</span><div><p className="menu-label">{t('home.observatory')}</p><strong>{t('home.chooseRoute')}</strong></div></header><button className="primary-button" onClick={onNewRun}>{t('newRun')} <span aria-hidden="true">→</span></button><button className="secondary-button" disabled={!hasSave} onClick={onContinue}>{t('home.continue')}{hasSave ? ` · Seed ${state.run?.seed}` : ''}</button><button className="secondary-button home-archive-button" onClick={onOpenCompendium}>{t('home.archive')} <span>{t('home.collected', { count: collected })}</span></button><button className="secondary-button home-custom-button" onClick={onOpenCustomContent}>{t('home.custom')} <span>{t('home.customDetail')}</span></button><button className="secondary-button home-monster-button" onClick={onOpenMonsterCompendium}>{t('home.monsterArchive')} <span>{t('home.monsterArchiveDetail')}</span></button><button className="secondary-button home-changelog-button" onClick={() => setChangelogOpen(true)}>{t('home.changelog')}</button><GameModal open={changelogOpen} onClose={() => setChangelogOpen(false)} title={t('home.changelog')} icon="🚀" variant="info"><ul className="changelog-list">{CHANGELOG.map((entry) => <li key={entry.date}><time>{entry.date}</time><span>{changelogText(entry.message)}</span></li>)}</ul></GameModal><div className="home-status-row"><span><b>{meta.upgradePoints}</b> {t('home.points')}</span><span>{hasSave ? t('home.saved') : t('home.ready')}</span></div><button className="text-button home-clear-button" disabled={!hasSave} onClick={onClearSave}>{t('home.clear')}</button></section></div><footer className="home-footer"><span>{t('home.footerDate')}</span><span>{t('home.footerSeed')}</span></footer></main>;
}
