import type { GameState } from '../game/engine/types';

interface HomePageProps { state: GameState; onNewRun: () => void; onContinue: () => void; onOpenCompendium: () => void; onOpenCustomContent: () => void; onClearSave: () => void; }
function HomeCosmos() { return <div className="home-cosmos" aria-hidden="true"><span className="home-eclipse" /><span className="home-rune-ring rune-ring-a" /><span className="home-rune-ring rune-ring-b" /><span className="home-meteor meteor-a" /><span className="home-meteor meteor-b" /><span className="home-meteor meteor-c" /><svg className="home-constellation" viewBox="0 0 300 300"><path d="M37 226L109 157 176 199 247 74M109 157L143 71M176 199L237 238" /><circle cx="37" cy="226" r="3" /><circle cx="109" cy="157" r="4" /><circle cx="143" cy="71" r="3" /><circle cx="176" cy="199" r="3" /><circle cx="247" cy="74" r="4" /><circle cx="237" cy="238" r="2.5" /></svg><span className="home-halo" /></div>; }
export function HomePage({ state, onNewRun, onContinue, onOpenCompendium, onOpenCustomContent, onClearSave }: HomePageProps) {
 const hasSave = state.run?.status === 'active'; const meta = state.metaProgress;
 const collected = meta.discoveredCharacterIds.length + meta.discoveredCardIds.length + meta.discoveredEnemyIds.length + meta.discoveredRelicIds.length + meta.discoveredPotionIds.length;
 return <main className="home-shell home-landing"><HomeCosmos /><div className="home-layout"><section className="title-block home-hero"><p className="eyebrow">THE CINDER EXPEDITION · VII</p><div className="title-sigil home-sigil" aria-hidden="true"><span>✦</span></div><h1>星陨牌局</h1><p className="subtitle">旧圣殿熄灭后的第七年，远行者以手中的牌与余烬订立契约。</p><p className="world-note">每一条路线、每一次抽牌，都由同一个 Seed 的命运织成。</p><div className="home-hero-rule"><span>EMBER / ORBITAL RECORD</span><i /></div><div className="home-ritual-readout" aria-label="远征仪式读数"><span><b>07</b>余烬纪年</span><span><b>Ⅰ</b>命运锚定</span><span><b>◌</b>圣殿静默</span></div></section><section className="menu-card home-command-card" aria-label="主菜单"><header className="home-command-head"><span className="home-command-mark" aria-hidden="true">✦</span><div><p className="menu-label">远征观测台</p><strong>选择你的下一道星轨</strong></div></header><button className="primary-button" onClick={onNewRun}>开始新的 Run <span aria-hidden="true">→</span></button><button className="secondary-button" disabled={!hasSave} onClick={onContinue}>继续游戏{hasSave ? ` · Seed ${state.run?.seed}` : ''}</button><button className="secondary-button home-archive-button" onClick={onOpenCompendium}>余烬图鉴 <span>已收集 {collected}</span></button><button className="secondary-button home-custom-button" onClick={onOpenCustomContent}>自定义内容 <span>编辑 / 导入 / 导出</span></button><div className="home-status-row"><span><b>{meta.upgradePoints}</b> 升级点</span><span>{hasSave ? '路线已封存' : '等待点火'}</span></div><button className="text-button home-clear-button" disabled={!hasSave} onClick={onClearSave}>抹除封存记录</button></section></div><footer className="home-footer"><span>星历 07 · 余烬仍在坠落</span><span>同一 Seed，保留同一命运</span></footer></main>;
}
