export type Locale = 'zh-CN' | 'en';
export const LOCALE_STORAGE_KEY = 'starfall-card-game/locale';
export const PAGE_TITLES: Record<Locale, string> = { 'zh-CN': '星陨牌局', en: 'Starfall Deckbuilder' };

type MessageTable = Record<string, string>;
export const messages: Record<Locale, MessageTable> = {
  'zh-CN': {
    'language.switch': '切换至 English', 'language.short': '中 / EN',
    'loading': '正在点燃余烬……', 'summary.eyebrow': '远征记录已封存', 'summary.victory': '余烬仍明', 'summary.defeat': '旅程终止', 'summary.stats': 'Seed {seed} · 难度 {difficulty} · 探索 {nodes} 个节点。', 'newRun': '开始新的 Run',
    'home.subtitle': '旧圣殿熄灭后的第七年，远行者以手中的牌与余烬订立契约。', 'home.worldNote': '每一条路线、每一次抽牌，都由同一个 Seed 的命运织成。', 'home.readout': '远征仪式读数', 'home.year': '余烬纪年', 'home.anchor': '命运锚定', 'home.silence': '圣殿静默', 'home.menu': '主菜单', 'home.observatory': '远征观测台', 'home.chooseRoute': '选择你的下一道星轨', 'home.continue': '继续游戏', 'home.archive': '余烬图鉴', 'home.collected': '已收集 {count}', 'home.custom': '自定义内容', 'home.customDetail': '编辑 / 导入 / 导出', 'home.points': '升级点', 'home.saved': '路线已封存', 'home.ready': '等待点火', 'home.clear': '抹除封存记录', 'home.footerDate': '星历 07 · 余烬仍在坠落', 'home.footerSeed': '同一 Seed，保留同一命运', 'home.changelog': '更新日志',
    'back': '返回', 'backHome': '返回主菜单',
    // CharacterSelectPage
    'character.title': '选择角色与难度', 'character.subtitle': '选择契约，再决定这次灰烬远征要承受怎样的试炼。', 'character.list': '角色列表', 'character.contract': '独特契约', 'character.hp': '生命', 'character.locked': '此契约尚未解锁', 'character.difficulty': '远征难度', 'character.open': '已开放 1–{level}', 'character.unlock3': '通关难度 3 后解锁', 'character.unlock4': '通关难度 4 后解锁', 'character.sealed': '封印中', 'character.region': '新地域：{regions}', 'character.selected': '已选契约 · 难度 {level}', 'character.startHp': '初始生命', 'character.energy': '初始能量', 'character.deck': '起始牌组', 'character.relic': '随身遗物', 'character.cards': '起始卡牌', 'character.cost': '消耗 {cost} 点能量', 'character.start': '以 {name} 开始 Run',
    // RewardPage
    'reward.eyebrow': '战利品已显现', 'reward.title': '战斗奖励', 'reward.copy': '已获得 {gold} 金币。选择一张卡牌加入牌组，或保留构筑并跳过。', 'reward.skip': '跳过卡牌，收下金币',
    // EventPage
    'event.eyebrow': '遗迹记录', 'event.noChange': '不改变{noun}', 'event.hp': '生命', 'event.gold': '金币', 'event.shortGold': '金币不足',
    // ShopPage
    'shop.eyebrow': '星尘行商 · 持有 {gold} 金币', 'shop.title': '灰市摊位', 'shop.copy': '行商只在余烬未熄时驻足。卡牌、药水和遗物每件仅能购置一次。', 'shop.card': '卡牌', 'shop.potion': '药水', 'shop.relic': '遗物', 'shop.service': '服务', 'shop.cost': '费用 {cost}', 'shop.unknown': '未知卡牌', 'shop.inCombat': '战斗中可使用', 'shop.remove': '剥离旧页', 'shop.removeDetail': '选择移除牌组中的一张卡牌', 'shop.removeCopy': '用于压缩构筑。', 'shop.upgrade': '重铸符文', 'shop.upgradeDetail': '选择升级一张未升级卡牌', 'shop.upgradeCopy': '数值提升会永久保留。', 'shop.relicDetail': '持有后持续生效', 'shop.shortfall': '还差 {gold}', 'shop.empty': '货架已经空了。你可以带着新货物继续远征。', 'shop.leave': '离开商店',
    // SpecialNodePage
    'special.rest': '余火整备', 'special.treasure': '封存遗藏', 'special.intermission': '幕间远征', 'special.leave': '不作选择，继续前进',
    // RunPage (map)
    'run.act': '第 {act} 幕', 'run.difficulty': '难度 {level}', 'run.title': '灰烬边境', 'run.routeLabel': '本幕固定地域顺序（可拖拽查看后续地域）', 'run.mapTitle': '远征地形图', 'run.mapHelper': '道路沿山脊、河谷与聚落展开。发亮路段是当前可通行路线；召回已走过道路后无法折返。', 'run.legendOpen': '可通行古道', 'run.legendFuture': '全部后续路线', 'run.legendTraveled': '已行经道路', 'run.legendRiver': '水系', 'run.legendContour': '等高线代表陡峭地势', 'run.elevation': '高程带 {row}', 'run.risk': '风险 {value}', 'run.reward': '回报 {value}', 'run.resource': '资源 {value}', 'run.supplies': '远征物资', 'run.statDifficulty': '难度', 'run.statHp': '生命', 'run.statGold': '金币', 'run.statDeck': '牌组', 'run.statDeckUnit': '{count} 张', 'run.statRelics': '遗物', 'run.statRelicsUnit': '{count} 件', 'run.seedNote': '地形、道路、地点和内容均由 Seeded RNG 推导；同一 Seed 保持相同测绘结果。', 'run.scaleUnit': '5 灰里', 'run.mapBureau': '熄火圣殿测绘局 · 远征版',
    // CombatPage
    'combat.turn': '回合 {turn}', 'combat.playerTurn': '你的行动', 'combat.enemyTurn': '敌人行动', 'combat.ended': '战斗结束', 'combat.victory': '余烬未灭', 'combat.defeat': '契约崩解', 'combat.corridor': '黑曜回廊', 'combat.hp': '生命', 'combat.energy': '能量', 'combat.block': '格挡', 'combat.leaveCombat': '离开战斗', 'combat.scene': '战斗场景', 'combat.enemyFormation': '敌人阵列', 'combat.frontline': '最前方', 'combat.frontTarget': '最前方目标', 'combat.rearGuard': '受到前排保护', 'combat.defeated': '已击败', 'combat.rearLabel': '前排保护', 'combat.resources': '角色资源', 'combat.phase': '阶段 {current}/{total}', 'combat.totalHp': '{name}总生命', 'combat.blockLabel': '格挡 {block}', 'combat.blockRetain': '格挡 {block} · 保留 {turns} 回合', 'combat.blockAria': '{name}格挡值', 'combat.blockRetainAria': '{name}格挡值，保留 {turns} 回合', 'combat.hpAria': '{name}生命值', 'combat.noStatus': '无状态', 'combat.retainInfo': '保留 {turns} 回合', 'combat.usePotion': '使用 {name}', 'combat.handHint': '拖拽卡牌至发光目标，或点击直接使用 · 单目标始终命中最前方', 'combat.piles': '抽牌 {draw} · 弃牌 {discard} · 消耗 {exhaust}', 'combat.hand': '手牌', 'combat.log': '战斗日志', 'combat.endTurn': '结束回合', 'combat.abandonConfirm': '确定要放弃本次冒险吗？当前进度将会丢失，无法恢复。', 'combat.abandonTitle': '放弃？', 'combat.abandonBody': '你确定要放弃本次冒险吗？所有进展都将丢失。', 'combat.abandonCancel': '取消', 'combat.abandonConfirmBtn': '放弃',
    // CompendiumPage
    'comp.title': '余烬图鉴', 'comp.subtitle': '未收集内容以灰色标记，但完整属性始终可查。每项首次收集都会获得 1 点升级点。', 'comp.points': '升级点', 'comp.upgradeCopy': '角色可强化生命、起始卡牌、初始能量与起始金币；强化只在下一次新 Run 生效。', 'comp.tabs': '图鉴分类', 'comp.characters': '角色特性', 'comp.cards': '卡牌', 'comp.enemies': '怪物', 'comp.relics': '遗物', 'comp.potions': '药水', 'comp.collected': '已收集 · +1 点', 'comp.notCollected': '未收集', 'comp.contract': '远征契约', 'comp.startHp': '初始生命', 'comp.startEnergy': '初始能量', 'comp.startGold': '起始金币', 'comp.starterDeck': '起始牌组', 'comp.deckUnit': '{count} 张；已强化 {upgraded}/{limit}', 'comp.startRelics': '起始遗物', 'comp.none': '无', 'comp.hpUpgrade': '{cost} 点：初始生命 +{amount}（{current}/{limit}）', 'comp.energyUpgrade': '{cost} 点：初始能量 +1（{current}/{limit}）', 'comp.goldUpgrade': '{cost} 点：起始金币 +{amount}（{current}/{limit}）', 'comp.upgraded': '✓ 已强化', 'comp.upgradeCard': '{cost} 点：强化', 'comp.keywords': '关键词', 'comp.upgrade': '升级', 'comp.noUpgrade': '无额外升级描述', 'comp.source': '出处', 'comp.enemyUnit': '敌对单位', 'comp.defaultAppearance': '系统默认外观', 'comp.customAppearance': '自定义内容使用系统默认外观。', 'comp.visualFeatures': '外貌特征', 'comp.enemyHp': '生命', 'comp.initBlock': '初始格挡', 'comp.actions': '行动', 'comp.noRecord': '无记录', 'comp.effect': '效果', 'comp.consumable': '消耗品', 'comp.rarity.basic': '基础', 'comp.rarity.common': '普通', 'comp.rarity.uncommon': '罕见', 'comp.rarity.rare': '稀有', 'comp.rarity.special': '特殊', 'comp.effect.strength': '力量 +{amount}', 'comp.effect.block': '格挡 +{amount}', 'comp.effect.gold': '金币 +{amount}', 'comp.effect.energy': '能量 {amount}', 'comp.effect.heal': '恢复生命 +{amount}', 'comp.effect.maxHp': '最大生命 +{amount}', 'comp.effect.damage': '伤害 {amount}{hits}（{target}）', 'comp.effect.draw': '抽牌 {amount}', 'comp.effect.applyStatus': '{status} {amount}{duration}（{target}）', 'comp.effect.cleanse': '净化：{statuses}', 'comp.effect.turns': ' · {amount} 回合', 'comp.effect.allEnemies': '所有敌人', 'comp.effect.frontEnemy': '最前方敌人', 'comp.effect.self': '自身', 'comp.effect.separator': '、', 'comp.trigger.on-combat-start': '战斗开始', 'comp.trigger.on-turn-start': '回合开始', 'comp.trigger.on-combat-end': '战斗结束',
    // CustomContentPage
    'cust.title': '余烬创作工坊', 'cust.subtitle': '像搭配牌组一样创建角色、卡牌、敌人、遗物和药水；不需要编写代码。', 'cust.playerMode': '玩家模式', 'cust.playerModeDesc': '使用 + / − 调整数量，直接在方框中输入数值；保存前会自动检查所有规则。', 'cust.contentType': '内容类型', 'cust.search': '搜索 {label}', 'cust.placeholder': '输入名称或标识', 'cust.filterLabel': '{label}细分分类', 'cust.showing': '显示 {count} 项', 'cust.entries': '内容条目', 'cust.noMatch': '没有符合条件的条目。', 'cust.create': '+ 创建新{label}', 'cust.loadExample': '载入完整卡牌示例', 'cust.editor': '玩家化编辑器 · {label}', 'cust.revert': '恢复内置', 'cust.save': '保存修改', 'cust.advanced': '高级模式：查看或编辑中文 JSON', 'cust.advancedNote': '普通玩家无需使用。修改后先点击"应用到表单"，再保存。', 'cust.advancedLabel': '高级中文自定义内容 JSON', 'cust.applyForm': '应用到玩家表单', 'cust.attrGuide': '属性与数值说明', 'cust.exportJson': '导出内容包', 'cust.exportTs': '导出代码格式', 'cust.import': '导入内容包', 'cust.reset': '一键复原为系统原版', 'cust.resetConfirm': '确认要清空所有自定义内容吗？操作不可撤销。', 'cust.resetDone': '已一键复原：所有自定义内容已清空，恢复为系统原版。', 'cust.ready': '玩家编辑器已就绪。使用按钮、选项和数值框组合内容，保存时仍会执行完整安全校验。', 'cust.editing': '正在编辑 {name}。所有改动会在点击保存后生效。', 'cust.saved': '已保存 {id}：本地存储回读验证成功，新战斗和图鉴将使用此配置。', 'cust.notSaved': '未保存：{reason}', 'cust.idRequired': '条目必须包含唯一标识。', 'cust.invalidContent': '内容无效。', 'cust.created': '已创建玩家模板。请修改名称、数值和组合后保存。', 'cust.showcaseLoaded': '已载入完整卡牌示例，可通过效果卡片逐项修改。', 'cust.reverted': '已恢复 {id} 的内置定义。', 'cust.noOverride': '当前条目没有自定义覆盖。', 'cust.cantRevert': '无法恢复。', 'cust.jsonApplied': '高级 JSON 已应用到玩家表单；点击"保存修改"后才会写入本地。', 'cust.jsonFail': '高级 JSON 无法应用：{reason}', 'cust.jsonInvalid': '格式无效。', 'cust.importSuccess': '导入成功：内容已验证并写入本地存储。', 'cust.importFail': '导入被拒绝，现有内容未改变：{reason}',
    // Category / filter labels used by CustomContentPage
    'cat.characters': '角色', 'cat.cards': '卡牌', 'cat.enemies': '敌人', 'cat.relics': '遗物', 'cat.potions': '药水',
    'filter.all': '全部', 'filter.highHp': '高生命', 'filter.largeDeck': '10+ 起始牌', 'filter.relicStart': '起始遗物', 'filter.potionStart': '起始药水', 'filter.attack': '攻击', 'filter.skill': '技艺', 'filter.power': '能力', 'filter.damage': '伤害', 'filter.block': '格挡', 'filter.buff': '增幅', 'filter.draw': '抽牌', 'filter.energy': '能量', 'filter.scaling': '资源缩放', 'filter.defend': '格挡', 'filter.status': '状态', 'filter.pollute': '污染', 'filter.summon': '召唤', 'filter.phase': '多阶段', 'filter.strength': '力量', 'filter.gold': '金币', 'filter.heal': '治疗', 'filter.maxHp': '最大生命', 'filter.combatStart': '战斗开始', 'filter.turnStart': '回合开始', 'filter.combatEnd': '战斗结束',
  },
  en: {
    'language.switch': 'Switch to 中文', 'language.short': 'EN / 中',
    'loading': 'Kindling the embers…', 'summary.eyebrow': 'Expedition record sealed', 'summary.victory': 'The embers endure', 'summary.defeat': 'The journey ends', 'summary.stats': 'Seed {seed} · Difficulty {difficulty} · {nodes} nodes explored.', 'newRun': 'Start a New Run',
    'home.subtitle': 'Seven years after the old sanctuary fell silent, a wanderer makes a pact with the ashes held in hand.', 'home.worldNote': 'Every route and every draw is woven by one Seed-bound fate.', 'home.readout': 'Expedition ritual readout', 'home.year': 'Ember calendar', 'home.anchor': 'Fate anchored', 'home.silence': 'Sanctum silent', 'home.menu': 'Main menu', 'home.observatory': 'Expedition observatory', 'home.chooseRoute': 'Choose your next starward path', 'home.continue': 'Continue Run', 'home.archive': 'Ember Compendium', 'home.collected': '{count} collected', 'home.custom': 'Custom Content', 'home.customDetail': 'Edit / import / export', 'home.points': 'Upgrade points', 'home.saved': 'Route sealed', 'home.ready': 'Awaiting ignition', 'home.clear': 'Erase sealed record', 'home.footerDate': 'Astral year 07 · embers still fall', 'home.footerSeed': 'Same Seed, same fate', 'home.changelog': 'Changelog',
    'back': 'Back', 'backHome': 'Back to main menu',
    'character.title': 'Choose a Character & Difficulty', 'character.subtitle': 'Choose a pact, then decide what trials this ashbound expedition must endure.', 'character.list': 'Character list', 'character.contract': 'Unique pact', 'character.hp': 'HP', 'character.locked': 'This pact is not unlocked yet', 'character.difficulty': 'Expedition Difficulty', 'character.open': 'Unlocked 1–{level}', 'character.unlock3': 'Unlock by clearing Difficulty 3', 'character.unlock4': 'Unlock by clearing Difficulty 4', 'character.sealed': 'Sealed', 'character.region': 'New region: {regions}', 'character.selected': 'Selected pact · Difficulty {level}', 'character.startHp': 'Starting HP', 'character.energy': 'Starting energy', 'character.deck': 'Starting deck', 'character.relic': 'Starting relic', 'character.cards': 'Starting cards', 'character.cost': 'Costs {cost} energy', 'character.start': 'Start Run as {name}',
    'reward.eyebrow': 'Spoils revealed', 'reward.title': 'Combat Reward', 'reward.copy': 'You gained {gold} gold. Choose a card to add to your deck, or preserve your build and skip.', 'reward.skip': 'Skip the card and take the gold',
    'event.eyebrow': 'Ruin record', 'event.noChange': 'No change to {noun}', 'event.hp': 'HP', 'event.gold': 'gold', 'event.shortGold': 'Not enough gold',
    'shop.eyebrow': 'Stardust merchant · {gold} gold held', 'shop.title': 'Ashmarket Stall', 'shop.copy': 'The merchant lingers only while the ember burns. Each card, potion, and relic can be bought once.', 'shop.card': 'Card', 'shop.potion': 'Potion', 'shop.relic': 'Relic', 'shop.service': 'Service', 'shop.cost': 'Cost {cost}', 'shop.unknown': 'Unknown card', 'shop.inCombat': 'Usable in combat', 'shop.remove': 'Strip Old Page', 'shop.removeDetail': 'Choose a card to remove from your deck', 'shop.removeCopy': 'Tighten your build.', 'shop.upgrade': 'Reforge Rune', 'shop.upgradeDetail': 'Choose an unupgraded card to upgrade', 'shop.upgradeCopy': 'Its improvement persists permanently.', 'shop.relicDetail': 'Active while held', 'shop.shortfall': '{gold} short', 'shop.empty': 'The shelves are empty. Continue your expedition with your new goods.', 'shop.leave': 'Leave shop',
    'special.rest': 'Ember Rest', 'special.treasure': 'Sealed Hoard', 'special.intermission': 'Between Acts', 'special.leave': 'Make no choice and move on',
    // RunPage
    'run.act': 'Act {act}', 'run.difficulty': 'Difficulty {level}', 'run.title': 'Ashen Frontier', 'run.routeLabel': 'Fixed region order for this act (drag to see later regions)', 'run.mapTitle': 'Expedition Terrain Map', 'run.mapHelper': 'Roads extend along ridges, valleys, and settlements. Lit segments are currently passable; once a road is left behind, it cannot be retraced.', 'run.legendOpen': 'Passable roads', 'run.legendFuture': 'All future routes', 'run.legendTraveled': 'Traveled roads', 'run.legendRiver': 'Water', 'run.legendContour': 'Contour lines mark steep terrain', 'run.elevation': 'Elevation band {row}', 'run.risk': 'Risk {value}', 'run.reward': 'Reward {value}', 'run.resource': 'Resource {value}', 'run.supplies': 'Expedition Supplies', 'run.statDifficulty': 'Difficulty', 'run.statHp': 'HP', 'run.statGold': 'Gold', 'run.statDeck': 'Deck', 'run.statDeckUnit': '{count} cards', 'run.statRelics': 'Relics', 'run.statRelicsUnit': '{count} held', 'run.seedNote': 'Terrain, roads, locations and content are all derived from a Seeded RNG; the same Seed yields the same map.', 'run.scaleUnit': '5 ash-miles', 'run.mapBureau': 'Cinder Cartographic Bureau · Expedition Ed.',
    // CombatPage
    'combat.turn': 'Turn {turn}', 'combat.playerTurn': 'Your action', 'combat.enemyTurn': 'Enemy action', 'combat.ended': 'Combat over', 'combat.victory': 'The embers endure', 'combat.defeat': 'Pact shattered', 'combat.corridor': 'Obsidian Corridor', 'combat.hp': 'HP', 'combat.energy': 'Energy', 'combat.block': 'Block', 'combat.leaveCombat': 'Leave combat', 'combat.scene': 'Combat scene', 'combat.enemyFormation': 'Enemy formation', 'combat.frontline': 'Frontline', 'combat.frontTarget': 'Frontline target', 'combat.rearGuard': 'Protected by front row', 'combat.defeated': 'Defeated', 'combat.rearLabel': 'Front guard', 'combat.resources': 'Character resources', 'combat.phase': 'Phase {current}/{total}', 'combat.totalHp': '{name} total HP', 'combat.blockLabel': 'Block {block}', 'combat.blockRetain': 'Block {block} · Retained {turns} turns', 'combat.blockAria': '{name} block', 'combat.blockRetainAria': '{name} block, retained {turns} turns', 'combat.hpAria': '{name} HP', 'combat.noStatus': 'No statuses', 'combat.retainInfo': 'retained {turns} turns', 'combat.usePotion': 'Use {name}', 'combat.handHint': 'Drag cards to glowing targets, or click to use · Single-target always hits frontline', 'combat.piles': 'Draw {draw} · Discard {discard} · Exhaust {exhaust}', 'combat.hand': 'Hand', 'combat.log': 'Combat log', 'combat.endTurn': 'End Turn', 'combat.abandonConfirm': 'Are you sure you want to abandon this run? All progress will be lost.', 'combat.abandonTitle': 'Abandon?', 'combat.abandonBody': 'Are you sure you want to abandon this run? All progress will be lost.', 'combat.abandonCancel': 'Cancel', 'combat.abandonConfirmBtn': 'Abandon',
    // CompendiumPage
    'comp.title': 'Ember Compendium', 'comp.subtitle': 'Uncollected items are greyed out but their stats are always visible. Each first discovery grants 1 upgrade point.', 'comp.points': 'Upgrade Points', 'comp.upgradeCopy': 'Characters can be upgraded for HP, starter cards, starting energy, and starting gold; upgrades apply on the next new Run.', 'comp.tabs': 'Compendium categories', 'comp.characters': 'Characters', 'comp.cards': 'Cards', 'comp.enemies': 'Enemies', 'comp.relics': 'Relics', 'comp.potions': 'Potions', 'comp.collected': 'Collected · +1 pt', 'comp.notCollected': 'Not collected', 'comp.contract': 'Expedition pact', 'comp.startHp': 'Starting HP', 'comp.startEnergy': 'Starting energy', 'comp.startGold': 'Starting gold', 'comp.starterDeck': 'Starting deck', 'comp.deckUnit': '{count} cards; {upgraded}/{limit} upgraded', 'comp.startRelics': 'Starting relics', 'comp.none': 'None', 'comp.hpUpgrade': '{cost} pt: Starting HP +{amount} ({current}/{limit})', 'comp.energyUpgrade': '{cost} pt: Starting energy +1 ({current}/{limit})', 'comp.goldUpgrade': '{cost} pt: Starting gold +{amount} ({current}/{limit})', 'comp.upgraded': '✓ Upgraded', 'comp.upgradeCard': '{cost} pt: Upgrade', 'comp.keywords': 'Keywords', 'comp.upgrade': 'Upgrade', 'comp.noUpgrade': 'No additional upgrade info', 'comp.source': 'Source', 'comp.enemyUnit': 'Hostile unit', 'comp.defaultAppearance': 'System default appearance', 'comp.customAppearance': 'Custom content uses the fixed system default appearance.', 'comp.visualFeatures': 'Visual features', 'comp.enemyHp': 'HP', 'comp.initBlock': 'Initial block', 'comp.actions': 'Actions', 'comp.noRecord': 'No record', 'comp.effect': 'Effect', 'comp.consumable': 'Consumable', 'comp.rarity.basic': 'Basic', 'comp.rarity.common': 'Common', 'comp.rarity.uncommon': 'Uncommon', 'comp.rarity.rare': 'Rare', 'comp.rarity.special': 'Special', 'comp.effect.strength': 'Strength +{amount}', 'comp.effect.block': 'Block +{amount}', 'comp.effect.gold': 'Gold +{amount}', 'comp.effect.energy': 'Energy {amount}', 'comp.effect.heal': 'Restore {amount} HP', 'comp.effect.maxHp': 'Max HP +{amount}', 'comp.effect.damage': 'Deal {amount} damage{hits} ({target})', 'comp.effect.draw': 'Draw {amount}', 'comp.effect.applyStatus': 'Apply {amount} {status}{duration} ({target})', 'comp.effect.cleanse': 'Cleanse: {statuses}', 'comp.effect.turns': ' · {amount} turns', 'comp.effect.allEnemies': 'all enemies', 'comp.effect.frontEnemy': 'front enemy', 'comp.effect.self': 'self', 'comp.effect.separator': ', ', 'comp.trigger.on-combat-start': 'Combat start', 'comp.trigger.on-turn-start': 'Turn start', 'comp.trigger.on-combat-end': 'Combat end',
    // CustomContentPage
    'cust.title': 'Ember Forge Workshop', 'cust.subtitle': 'Create characters, cards, enemies, relics and potions like building a deck — no coding needed.', 'cust.playerMode': 'Player Mode', 'cust.playerModeDesc': 'Use + / − to adjust values, type directly in boxes; all rules are validated before saving.', 'cust.contentType': 'Content types', 'cust.search': 'Search {label}', 'cust.placeholder': 'Enter name or ID', 'cust.filterLabel': '{label} sub-filters', 'cust.showing': 'Showing {count} items', 'cust.entries': 'Content entries', 'cust.noMatch': 'No matching entries.', 'cust.create': '+ Create new {label}', 'cust.loadExample': 'Load full card example', 'cust.editor': 'Player editor · {label}', 'cust.revert': 'Revert to built-in', 'cust.save': 'Save changes', 'cust.advanced': 'Advanced: view or edit JSON', 'cust.advancedNote': 'Not needed for normal players. Click "Apply to form" first, then save.', 'cust.advancedLabel': 'Advanced custom content JSON', 'cust.applyForm': 'Apply to player form', 'cust.attrGuide': 'Attribute & value reference', 'cust.exportJson': 'Export content pack', 'cust.exportTs': 'Export code format', 'cust.import': 'Import content pack', 'cust.reset': 'Reset all to defaults', 'cust.resetConfirm': 'Are you sure you want to clear ALL custom content? This cannot be undone.', 'cust.resetDone': 'All custom content cleared, restored to system defaults.', 'cust.ready': 'Player editor ready. Use buttons, options and number fields to compose content; full validation runs on save.', 'cust.editing': 'Editing {name}. Changes take effect after saving.', 'cust.saved': '{id} saved: local storage read-back passed; new combats and compendium will use this config.', 'cust.notSaved': 'Not saved: {reason}', 'cust.idRequired': 'Entry must have a unique ID.', 'cust.invalidContent': 'Invalid content.', 'cust.created': 'Player template created. Modify name, values and composition, then save.', 'cust.showcaseLoaded': 'Full card example loaded; modify individual effect tiles.', 'cust.reverted': '{id} reverted to built-in definition.', 'cust.noOverride': 'This entry has no custom override.', 'cust.cantRevert': 'Cannot revert.', 'cust.jsonApplied': 'Advanced JSON applied to player form; click "Save changes" to persist.', 'cust.jsonFail': 'Advanced JSON could not be applied: {reason}', 'cust.jsonInvalid': 'Invalid format.', 'cust.importSuccess': 'Import successful: content validated and written to local storage.', 'cust.importFail': 'Import rejected, existing content unchanged: {reason}',
    'cat.characters': 'Characters', 'cat.cards': 'Cards', 'cat.enemies': 'Enemies', 'cat.relics': 'Relics', 'cat.potions': 'Potions',
    'filter.all': 'All', 'filter.highHp': 'High HP', 'filter.largeDeck': '10+ Starters', 'filter.relicStart': 'Starting relic', 'filter.potionStart': 'Starting potion', 'filter.attack': 'Attack', 'filter.skill': 'Skill', 'filter.power': 'Power', 'filter.damage': 'Damage', 'filter.block': 'Block', 'filter.buff': 'Buff', 'filter.draw': 'Draw', 'filter.energy': 'Energy', 'filter.scaling': 'Scaling', 'filter.defend': 'Block', 'filter.status': 'Status', 'filter.pollute': 'Pollute', 'filter.summon': 'Summon', 'filter.phase': 'Multi-phase', 'filter.strength': 'Strength', 'filter.gold': 'Gold', 'filter.heal': 'Heal', 'filter.maxHp': 'Max HP', 'filter.combatStart': 'Combat start', 'filter.turnStart': 'Turn start', 'filter.combatEnd': 'Combat end',
  },
};
