export type Locale = 'zh-CN' | 'en';
export const LOCALE_STORAGE_KEY = 'starfall-card-game/locale';
export const PAGE_TITLES: Record<Locale, string> = { 'zh-CN': '星陨牌局', en: 'Starfall Deckbuilder' };

type MessageTable = Record<string, string>;
export const messages: Record<Locale, MessageTable> = {
  'zh-CN': {
    'language.switch': '切换至 English', 'language.short': '中 / EN',
    'loading': '正在点燃余烬……', 'summary.eyebrow': '远征记录已封存', 'summary.victory': '余烬仍明', 'summary.defeat': '旅程终止', 'summary.stats': 'Seed {seed} · 难度 {difficulty} · 探索 {nodes} 个节点。', 'newRun': '开始新的 Run',
    'home.subtitle': '旧圣殿熄灭后的第七年，远行者以手中的牌与余烬订立契约。', 'home.worldNote': '每一条路线、每一次抽牌，都由同一个 Seed 的命运织成。', 'home.readout': '远征仪式读数', 'home.year': '余烬纪年', 'home.anchor': '命运锚定', 'home.silence': '圣殿静默', 'home.menu': '主菜单', 'home.observatory': '远征观测台', 'home.chooseRoute': '选择你的下一道星轨', 'home.continue': '继续游戏', 'home.archive': '余烬图鉴', 'home.collected': '已收集 {count}', 'home.custom': '自定义内容', 'home.customDetail': '编辑 / 导入 / 导出', 'home.points': '升级点', 'home.saved': '路线已封存', 'home.ready': '等待点火', 'home.clear': '抹除封存记录', 'home.footerDate': '星历 07 · 余烬仍在坠落', 'home.footerSeed': '同一 Seed，保留同一命运',
    'back': '返回', 'backHome': '返回主菜单', 'character.title': '选择角色与难度', 'character.subtitle': '选择契约，再决定这次灰烬远征要承受怎样的试炼。', 'character.list': '角色列表', 'character.contract': '独特契约', 'character.hp': '生命', 'character.locked': '此契约尚未解锁', 'character.difficulty': '远征难度', 'character.open': '已开放 1–{level}', 'character.unlock3': '通关难度 3 后解锁', 'character.unlock4': '通关难度 4 后解锁', 'character.sealed': '封印中', 'character.region': '新地域：{regions}', 'character.selected': '已选契约 · 难度 {level}', 'character.startHp': '初始生命', 'character.energy': '初始能量', 'character.deck': '起始牌组', 'character.relic': '随身遗物', 'character.cards': '起始卡牌', 'character.cost': '消耗 {cost} 点能量', 'character.start': '以 {name} 开始 Run',
    'reward.eyebrow': '战利品已显现', 'reward.title': '战斗奖励', 'reward.copy': '已获得 {gold} 金币。选择一张卡牌加入牌组，或保留构筑并跳过。', 'reward.skip': '跳过卡牌，收下金币',
    'event.eyebrow': '遗迹记录', 'event.noChange': '不改变{noun}', 'event.hp': '生命', 'event.gold': '金币', 'event.shortGold': '金币不足',
    'shop.eyebrow': '星尘行商 · 持有 {gold} 金币', 'shop.title': '灰市摊位', 'shop.copy': '行商只在余烬未熄时驻足。卡牌、药水和遗物每件仅能购置一次。', 'shop.card': '卡牌', 'shop.potion': '药水', 'shop.relic': '遗物', 'shop.service': '服务', 'shop.cost': '费用 {cost}', 'shop.unknown': '未知卡牌', 'shop.inCombat': '战斗中可使用', 'shop.remove': '剥离旧页', 'shop.removeDetail': '选择移除牌组中的一张卡牌', 'shop.removeCopy': '用于压缩构筑。', 'shop.upgrade': '重铸符文', 'shop.upgradeDetail': '选择升级一张未升级卡牌', 'shop.upgradeCopy': '数值提升会永久保留。', 'shop.relicDetail': '持有后持续生效', 'shop.shortfall': '还差 {gold}', 'shop.empty': '货架已经空了。你可以带着新货物继续远征。', 'shop.leave': '离开商店',
    'special.rest': '余火整备', 'special.treasure': '封存遗藏', 'special.intermission': '幕间远征', 'special.leave': '不作选择，继续前进',
  },
  en: {
    'language.switch': 'Switch to 中文', 'language.short': 'EN / 中',
    'loading': 'Kindling the embers…', 'summary.eyebrow': 'Expedition record sealed', 'summary.victory': 'The embers endure', 'summary.defeat': 'The journey ends', 'summary.stats': 'Seed {seed} · Difficulty {difficulty} · {nodes} nodes explored.', 'newRun': 'Start a New Run',
    'home.subtitle': 'Seven years after the old sanctuary fell silent, a wanderer makes a pact with the ashes held in hand.', 'home.worldNote': 'Every route and every draw is woven by one Seed-bound fate.', 'home.readout': 'Expedition ritual readout', 'home.year': 'Ember calendar', 'home.anchor': 'Fate anchored', 'home.silence': 'Sanctum silent', 'home.menu': 'Main menu', 'home.observatory': 'Expedition observatory', 'home.chooseRoute': 'Choose your next starward path', 'home.continue': 'Continue Run', 'home.archive': 'Ember Compendium', 'home.collected': '{count} collected', 'home.custom': 'Custom Content', 'home.customDetail': 'Edit / import / export', 'home.points': 'Upgrade points', 'home.saved': 'Route sealed', 'home.ready': 'Awaiting ignition', 'home.clear': 'Erase sealed record', 'home.footerDate': 'Astral year 07 · embers still fall', 'home.footerSeed': 'Same Seed, same fate',
    'back': 'Back', 'backHome': 'Back to main menu', 'character.title': 'Choose a Character & Difficulty', 'character.subtitle': 'Choose a pact, then decide what trials this ashbound expedition must endure.', 'character.list': 'Character list', 'character.contract': 'Unique pact', 'character.hp': 'HP', 'character.locked': 'This pact is not unlocked yet', 'character.difficulty': 'Expedition Difficulty', 'character.open': 'Unlocked 1–{level}', 'character.unlock3': 'Unlock by clearing Difficulty 3', 'character.unlock4': 'Unlock by clearing Difficulty 4', 'character.sealed': 'Sealed', 'character.region': 'New region: {regions}', 'character.selected': 'Selected pact · Difficulty {level}', 'character.startHp': 'Starting HP', 'character.energy': 'Starting energy', 'character.deck': 'Starting deck', 'character.relic': 'Starting relic', 'character.cards': 'Starting cards', 'character.cost': 'Costs {cost} energy', 'character.start': 'Start Run as {name}',
    'reward.eyebrow': 'Spoils revealed', 'reward.title': 'Combat Reward', 'reward.copy': 'You gained {gold} gold. Choose a card to add to your deck, or preserve your build and skip.', 'reward.skip': 'Skip the card and take the gold',
    'event.eyebrow': 'Ruin record', 'event.noChange': 'No change to {noun}', 'event.hp': 'HP', 'event.gold': 'gold', 'event.shortGold': 'Not enough gold',
    'shop.eyebrow': 'Stardust merchant · {gold} gold held', 'shop.title': 'Ashmarket Stall', 'shop.copy': 'The merchant lingers only while the ember burns. Each card, potion, and relic can be bought once.', 'shop.card': 'Card', 'shop.potion': 'Potion', 'shop.relic': 'Relic', 'shop.service': 'Service', 'shop.cost': 'Cost {cost}', 'shop.unknown': 'Unknown card', 'shop.inCombat': 'Usable in combat', 'shop.remove': 'Strip Old Page', 'shop.removeDetail': 'Choose a card to remove from your deck', 'shop.removeCopy': 'Tighten your build.', 'shop.upgrade': 'Reforge Rune', 'shop.upgradeDetail': 'Choose an unupgraded card to upgrade', 'shop.upgradeCopy': 'Its improvement persists permanently.', 'shop.relicDetail': 'Active while held', 'shop.shortfall': '{gold} short', 'shop.empty': 'The shelves are empty. Continue your expedition with your new goods.', 'shop.leave': 'Leave shop',
    'special.rest': 'Ember Rest', 'special.treasure': 'Sealed Hoard', 'special.intermission': 'Between Acts', 'special.leave': 'Make no choice and move on',
  },
};
