import { create } from 'zustand';
import { CARD_CATALOG } from '../data/cards/basicCards'; import { CHARACTERS } from '../data/characters/characters'; import { selectEncounter } from '../data/encounters/basicEncounters'; import { selectEvent } from '../data/events/basicEvents'; import { BASIC_POTIONS } from '../data/potions/basicPotions'; import { createShop } from '../data/shops/basicShops';
import { applyCharacterUpgrades, recordDiscoveries, spendEnergyPoint, spendGoldPoint, spendHpPoint, spendStarterCardUpgradePoint } from '../game/ascension/collectionEngine'; import { createMetaProgress, recordVictory } from '../game/ascension/metaEngine';
import type { CardDefinition } from '../game/combat/cardTypes'; import { playCardAndResolve, finishPlayerTurn, resolveEnemyTurn, startCombat } from '../game/combat/combatEngine'; import { persistentCards, createCardInstance } from '../game/combat/deckEngine'; import type { GameState, PlayerState, SpecialNodeState } from '../game/engine/types'; import { GAME_SCHEMA_VERSION } from '../game/engine/types'; import { attemptMove, generateMap, moveToNode } from '../game/map/mapGenerator'; import type { InvalidMoveReason, MapNode } from '../game/map/mapTypes'; import { usePotion as usePotionInCombat } from '../game/potion/potionEngine'; import { createReplay, finalizeReplay, recordReplayAction } from '../game/replay/replayEngine'; import { createRun } from '../game/run/createRun';
import { nodeSeed } from '../game/run/nodeSeed'; import { createReward } from '../game/run/contentSelection';
import { loadCustomContent } from '../game/content/customContent';
import { loadGame, saveGame } from '../game/save/saveSystem';
import { applyDeckOperation, eventDeckOperation } from '../game/run/deckOperations';
interface GameStore { gameState: GameState; hydrated: boolean; hydrate: () => void; newRun: (seed?: number, characterId?: string) => void; openCharacterSelect: (open?: boolean) => void; openCompendium: (open?: boolean) => void; openCustomContent: (open?: boolean) => void; spendHpUpgrade: (characterId: string) => void; spendStarterCardUpgrade: (characterId: string, cardIndex: number) => void; spendEnergyUpgrade: (characterId: string) => void; spendGoldUpgrade: (characterId: string) => void; startRun: (characterId: string) => void; startTestCombat: () => void; enterNode: (nodeId: string) => void; tryEnterNode: (nodeId: string) => InvalidMoveReason; playCard: (cardUid: string, definition: CardDefinition, targetUid?: string) => void; endTurn: () => void; usePotion: (potionId: string) => void; claimReward: (cardId?: string) => void; chooseEvent: (choiceId: string, cardUid?: string) => void; buyShopCard: (itemId: string, price: number, cardUid?: string) => void; chooseSpecial: (choiceId: string, cardUid?: string) => void; leaveSpecialNode: () => void; exitCombat: () => void; continueRun: () => void; clearSave: () => void; }
function defaultMeta() { return { ...createMetaProgress(), unlockedCharacterIds: Object.keys(CHARACTERS), unlockedCardIds: Object.keys(CARD_CATALOG), unlockedRelicIds: ['ember-seal', 'coin-orbit'] }; }
function home(metaProgress = defaultMeta()): GameState { return { schemaVersion: GAME_SCHEMA_VERSION, mode: 'home', seed: null, run: null, player: null, metaProgress }; }
function persist(set: (state: { gameState: GameState }) => void, state: GameState): void { const discovered = recordDiscoveries(state); const next = discovered.replay ? { ...discovered, replay: finalizeReplay(discovered.replay, discovered) } : discovered; saveGame(next); set({ gameState: next }); }
function record(state: GameState, type: Parameters<typeof recordReplayAction>[1]['type'], payload: Record<string, string | number | undefined> = {}): GameState { return state.replay ? { ...state, replay: recordReplayAction(state.replay, { type, payload }) } : state; }
function cardFor(player: PlayerState, id: string, prefix: string): PlayerState { const baseUid = `${prefix}-${player.deck.length}-${id}`; let uid = baseUid; for (let suffix = 1; player.deck.some((card) => card.uid === uid); suffix += 1) uid = `${baseUid}-${suffix}`; return { ...player, deck: [...player.deck, createCardInstance(id, uid)] }; }
function afterCombat(state: GameState, combat: NonNullable<GameState['combat']>): GameState {
 const maxHp = state.player!.maxHp + combat.persistentMaxHpDelta;
 const player = { ...state.player!, maxHp, hp: Math.min(maxHp, combat.player.hp), gold: state.player!.gold + combat.persistentGoldDelta, potions: combat.potionIds, deck: persistentCards(combat.deck) };
 const node = state.map?.nodes.find((candidate) => candidate.id === state.run?.currentNodeId);
 if (!node || !state.map) return { ...state, mode: 'map', player, combat: undefined };
 if (combat.phase === 'defeat') return { ...state, mode: 'run-summary', player, combat: undefined, run: { ...state.run!, status: 'defeat' } };
 if (node.type !== 'boss') { const profile = state.player!.characterId.startsWith('legacy-') ? 'legacy' : 'native'; return { ...state, mode: 'reward', player, combat: undefined, reward: createReward(nodeSeed(state.seed!, node), node.row, node.type === 'elite', state.map.biomeId, profile) }; }
 const nextAct = state.run!.currentAct + 1;
 if (nextAct > 3) return { ...state, mode: 'run-summary', player, combat: undefined, run: { ...state.run!, status: 'victory' }, metaProgress: recordVictory(state.metaProgress) };
 const map = generateMap(state.seed!, undefined, nextAct);
 const special: SpecialNodeState = { nodeType: 'intermission', title: `第 ${nextAct} 幕：余烬更深处`, description: '守门者已倒下。整备牌组后，新的道路将按同一 Seed 延续。', choices: [{ id: 'continue', label: '踏入下一幕', description: '保留所有卡牌、遗物与药水，进入新的分支地图。', kind: 'skip' }] };
 return { ...state, mode: 'special', player, combat: undefined, map, special, run: { ...state.run!, currentAct: nextAct, currentNodeId: null, visitedNodeIds: [] } };
}
export const useGameStore = create<GameStore>((set, get) => ({ gameState: home(), hydrated: false,
 hydrate: () => { try { loadCustomContent(); } catch { /* Invalid user content remains inactive; the game keeps its built-in registry. */ } const loaded = loadGame() ?? home(); const state = recordDiscoveries(loaded); if (state !== loaded) saveGame(state); set({ gameState: state, hydrated: true }); },
 newRun: (seed = Date.now() >>> 0, characterId = 'wanderer') => { const previous = get().gameState; const baseCharacter = CHARACTERS[characterId] ?? CHARACTERS.wanderer; const character = applyCharacterUpgrades(baseCharacter, previous.metaProgress.characterUpgrades[baseCharacter.id]); const state = createRun(seed, Date.now(), character, previous.metaProgress.ascensionLevel, previous.metaProgress.characterUpgrades[baseCharacter.id]?.starterCardUpgradeIndexes); persist(set, { ...state, metaProgress: previous.metaProgress, replay: recordReplayAction(createReplay(seed), { type: 'start-run', payload: { characterId } }) }); },
 openCharacterSelect: (open = true) => set({ gameState: { ...get().gameState, mode: open ? 'character-select' : 'home' } }),
 openCompendium: (open = true) => set({ gameState: { ...get().gameState, mode: open ? 'compendium' : 'home' } }),
 openCustomContent: (open = true) => set({ gameState: { ...get().gameState, mode: open ? 'custom-content' : 'home' } }),
 spendHpUpgrade: (characterId) => { const raw = get().gameState; const metaProgress = spendHpPoint(raw.metaProgress, characterId); if (metaProgress) persist(set, { ...raw, metaProgress }); },
 spendStarterCardUpgrade: (characterId, cardIndex) => { const raw = get().gameState; const metaProgress = spendStarterCardUpgradePoint(raw.metaProgress, characterId, cardIndex); if (metaProgress) persist(set, { ...raw, metaProgress }); },
 spendEnergyUpgrade: (characterId) => { const raw = get().gameState; const metaProgress = spendEnergyPoint(raw.metaProgress, characterId); if (metaProgress) persist(set, { ...raw, metaProgress }); },
 spendGoldUpgrade: (characterId) => { const raw = get().gameState; const metaProgress = spendGoldPoint(raw.metaProgress, characterId); if (metaProgress) persist(set, { ...raw, metaProgress }); },
 startRun: (id) => { if (CHARACTERS[id]) get().newRun(undefined, id); }, startTestCombat: () => { const id = get().gameState.map?.availableNodeIds[0]; if (id) get().enterNode(id); },
 enterNode: (nodeId) => {
  const raw = get().gameState; if (!raw.map || !raw.run || !raw.player || raw.seed === null) return;
  try {
   const map = moveToNode(raw.map, nodeId); const node = map.nodes.find((candidate) => candidate.id === nodeId); if (!node) return;
   const contentSeed = nodeSeed(raw.seed, node); const biomeId = map.biomeId; let destination: Partial<GameState>;
   if (node.type === 'combat' || node.type === 'elite' || node.type === 'boss') {
    const tier = node.type === 'boss' ? 'boss' : node.type === 'elite' ? 'elite' : 'combat';
    const enemies = selectEncounter(contentSeed, tier, node.row, raw.run.currentAct, biomeId, raw.player.characterId.startsWith('legacy-') ? 'legacy' : 'native');
    destination = { mode: 'combat', combat: startCombat(raw.player, contentSeed, enemies, raw.run.ascensionLevel) };
   } else if (node.type === 'event') destination = { mode: 'event', event: selectEvent(contentSeed, node.row, biomeId) };
   else if (node.type === 'shop') destination = { mode: 'shop', shop: createShop(contentSeed, node.row, biomeId) };
   else { const special: SpecialNodeState = node.type === 'rest' ? { nodeType: 'rest', title: '熄火壁炉', description: '余火尚存；你只能选择一次整备。', choices: [{ id: 'heal', label: '温养伤口', description: '恢复 18 点生命。', kind: 'heal', amount: 18 }, { id: 'upgrade', label: '锻打卡牌', description: '选择牌组中的一张未升级卡牌。', kind: 'upgrade' }] } : { nodeType: 'treasure', title: '封存遗藏', description: '石匣中只容一项馈赠。', choices: [{ id: 'gold', label: '取走星币', description: '获得 55 金币。', kind: 'gold', amount: 55 }, { id: 'relic', label: '取走印记', description: '获得余烬印记。', kind: 'relic', relicId: 'ember-seal' }] }; destination = { mode: 'special', special }; }
   const base = record({ ...raw, map, run: { ...raw.run, currentNodeId: node.id, visitedNodeIds: map.visitedNodeIds }, event: undefined, shop: undefined, special: undefined }, 'enter-node', { nodeId });
   persist(set, { ...base, ...destination });
  } catch { return; }
 },
 tryEnterNode: (nodeId) => { const raw = get().gameState; if (!raw.map) return 'INVALID_NODE'; const attempt = attemptMove(raw.map, nodeId); if (!attempt.ok) return attempt.reason; get().enterNode(nodeId); return 'NONE'; },
 playCard: (cardUid, given, targetUid) => { const raw = get().gameState; const definition = CARD_CATALOG[given.id]; if (!raw.combat || !definition || !raw.combat.deck.hand.some((card) => card.uid === cardUid && card.definitionId === definition.id)) return; try { const combat = playCardAndResolve(raw.combat, cardUid, definition, targetUid); const next = record(combat.phase === 'victory' ? afterCombat(raw, combat) : { ...raw, combat }, 'play-card', { cardUid, targetUid }); persist(set, next); } catch { return; } },
 endTurn: () => { const raw = get().gameState; if (!raw.combat || raw.combat.phase !== 'player-turn') return; const combat = resolveEnemyTurn(finishPlayerTurn(raw.combat)); persist(set, record(combat.phase === 'defeat' ? afterCombat(raw, combat) : { ...raw, combat }, 'end-turn')); },
 usePotion: (potionId) => { const raw = get().gameState; const potion = BASIC_POTIONS[potionId]; if (!raw.combat || !potion || !raw.combat.potionIds.includes(potionId)) return; const combat = usePotionInCombat(raw.combat, potion); persist(set, record(combat.phase === 'victory' ? afterCombat(raw, combat) : { ...raw, combat }, 'use-potion', { potionId })); },
 claimReward: (cardId) => { const raw = get().gameState; if (!raw.reward || !raw.player || (cardId && !raw.reward.cardChoices.includes(cardId))) return; let player = { ...raw.player, gold: raw.player.gold + raw.reward.gold }; if (cardId) player = cardFor(player, cardId, `reward-${raw.run?.id}`); persist(set, record({ ...raw, mode: 'map', player, reward: undefined }, 'claim-reward', { cardId })); },
 chooseEvent: (choiceId, cardUid) => { const raw = get().gameState; const choice = raw.event?.choices.find((candidate) => candidate.id === choiceId); if (!choice || !raw.player || (choice.goldDelta < 0 && raw.player.gold < -choice.goldDelta)) return; const operation = eventDeckOperation(choice); if (operation && !cardUid) return; let deck = raw.player.deck; if (operation) try { deck = applyDeckOperation(deck, operation, cardUid!); } catch { return; } let player: PlayerState = { ...raw.player, deck, hp: Math.max(1, Math.min(raw.player.maxHp, raw.player.hp + choice.hpDelta)), gold: raw.player.gold + choice.goldDelta }; if (choice.addCardId) player = cardFor(player, choice.addCardId, `event-${raw.run?.id}`); if (choice.relicId && !player.relics.includes(choice.relicId)) player.relics = [...player.relics, choice.relicId]; if (choice.potionId) player.potions = [...player.potions, choice.potionId]; persist(set, record({ ...raw, mode: 'map', player, event: undefined }, 'event-choice', { choiceId, cardUid })); },
 buyShopCard: (itemId, price, cardUid) => { const raw = get().gameState; const item = raw.shop?.items.find((candidate) => candidate.id === itemId); if (!raw.player || !item || item.price !== price || raw.player.gold < price) return; let deck = raw.player.deck; if (item.kind === 'remove' || item.kind === 'upgrade') { if (!cardUid) return; try { deck = applyDeckOperation(deck, item.kind, cardUid); } catch { return; } } let player: PlayerState = { ...raw.player, deck, gold: raw.player.gold - price }; if (item.kind === 'card') player = cardFor(player, item.id, `shop-${raw.run?.id}`); else if (item.kind === 'potion') player.potions = [...player.potions, item.id]; else if (item.kind === 'relic') player.relics = [...player.relics, item.id]; persist(set, record({ ...raw, player, shop: { items: raw.shop!.items.filter((candidate) => candidate !== item) } }, 'shop-purchase', { itemId, cardUid })); },
 chooseSpecial: (choiceId, cardUid) => { const raw = get().gameState; const choice = raw.special?.choices.find((candidate) => candidate.id === choiceId); if (!choice || !raw.player) return; let deck = raw.player.deck; if (choice.kind === 'upgrade') { if (!cardUid) return; try { deck = applyDeckOperation(deck, 'upgrade', cardUid); } catch { return; } } let player: PlayerState = { ...raw.player, deck }; if (choice.kind === 'heal') player.hp = Math.min(player.maxHp, player.hp + (choice.amount ?? 0)); if (choice.kind === 'gold') player.gold += choice.amount ?? 0; if (choice.kind === 'relic' && choice.relicId && !player.relics.includes(choice.relicId)) player.relics = [...player.relics, choice.relicId]; persist(set, record({ ...raw, mode: 'map', player, special: undefined }, 'special-choice', { choiceId, cardUid })); },
 leaveSpecialNode: () => { const raw = get().gameState; persist(set, record({ ...raw, mode: 'map', shop: undefined, event: undefined, special: undefined }, 'leave-special')); }, exitCombat: () => { const raw = get().gameState; if (!raw.combat || (raw.combat.phase !== 'victory' && raw.combat.phase !== 'defeat')) return; persist(set, afterCombat(raw, raw.combat)); }, continueRun: () => set({ gameState: { ...get().gameState, mode: get().gameState.map ? 'map' : 'home' } }), clearSave: () => { const state = home(get().gameState.metaProgress); saveGame(state); set({ gameState: state }); },
}));
