import type { BiomeId } from '../../data/biomes/biomes';

export type MapNodeType = 'start' | 'combat' | 'elite' | 'rest' | 'shop' | 'event' | 'treasure' | 'special' | 'boss';
export type MapLocationKind = 'trail' | 'village' | 'waystation' | 'ruin' | 'crossing' | 'outpost' | 'sanctum';

export interface NodeScore { risk: number; reward: number; resource: number; difficulty: number; }

export interface MapNode extends NodeScore {
  id: string;
  row: number;
  column: number;
  x: number;
  y: number;
  type: MapNodeType;
  locationKind: MapLocationKind;
  locationName: string;
  /** Fixed campaign region for this row. Old saves may omit it. */
  regionId?: BiomeId;
  connections: string[];
  parents: string[];
}

/** Visual-only deterministic Bézier controls. Old saves may omit these fields. */
export interface MapEdge {
  from: string;
  to: string;
  control1X?: number;
  control1Y?: number;
  control2X?: number;
  control2Y?: number;
}

export interface MapState {
  mapId: string;
  seed: number;
  act: number;
  biomeId: BiomeId;
  generationVersion: number;
  /** Persisted route-depth contract for maps generated by v3+. */
  minRouteLength?: number;
  maxRouteLength?: number;
  nodes: MapNode[];
  edges: MapEdge[];
  currentNodeId: string | null;
  visitedNodeIds: string[];
  availableNodeIds: string[];
  completedNodeIds: string[];
  bossNodeId: string;
}

export type InvalidMoveReason = 'NONE' | 'NOT_CONNECTED' | 'ALREADY_VISITED' | 'INVALID_NODE' | 'CURRENT_NODE_NOT_COMPLETE';
export type NodeStatus = 'completed' | 'current' | 'available' | 'visited' | 'locked';
